---
# portainer_container_data_dir_sub_folders:
#   - "etc-portainer/"
#   - "mnt-backup/"
#   - "scripts"

portainer_container_volumes:
  binds:
    - source: "/var/run/docker.sock"
      target: "/var/run/docker.sock"
    - source: "portainer_data"
      target: "/data"
  volumes:
    - "portainer_data"
