---
- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ smtp_relay_container_name }}"
  register: smtp_relay_container_state

- name: "TASK: Set container facts"
  set_fact:
    smtp_relay_container_exists: "{{ smtp_relay_container_state.exists }}"
    smtp_relay_container_image: "{{ smtp_relay_container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    smtp_relay_container_image_tag: "{{ smtp_relay_container_image.split(':') }}"

- block:
    - include_tasks: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ smtp_relay_image_base }}"
        tag: "{{ smtp_relay_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "smtp_relay_image_base_pull"
  when: smtp_relay_container_image_tag[1] != smtp_relay_image_base_tag

- name: "TASK: Delete {{ smtp_relay_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ smtp_relay_container_data_dir }}"
    state: "absent"
  when: image_base_pull.changed or container_templated_files.changed
  register: container_deleted

- name: "TASK: Deploy {{ smtp_relay_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ smtp_relay_container_data_dir }}"
    state: "{{ 'restarted' if smtp_relay_container_restart and not container_deleted.changed else 'present' }}"
