---

- name: "Create folders for build and container data"
  file:
    path: "{{ smtp_relay_container_data_dir }}"
    state: "directory"

- name: "Template files for building and running {{ smtp_relay_container_name }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "docker"
    mode: 0660
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ smtp_relay_container_data_dir }}/docker-compose.yml"
    - src: "smtp_relay.env.j2"
      dest: "{{ smtp_relay_container_data_dir }}/smtp_relay.env"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "TASK: Set containers to restart when templated files change"
  set_fact:
    smtp_relay_container_restart: "yes"
  when: "container_templated_files.changed"
