---
- name: Baseline setup
  hosts: localhost
  connection: local
  gather_facts: true
  ignore_errors: false

  roles:
    ### User-related
    - "clone-my-repos"
    - "configure-docker"
    - "configure-smb4k"
    - "configure-wake-from-suspend"
    - "create-home-links"
    - "update-homeConfig-files"
