ansible_become_password: "{{ vault_ansible_become_password }}"
### Only used when initializing Proxmox hosts without users configured
# ansible_user: root

sudoer_identities: "{{ vault_sudoer_identities }}"
