docker_data_dir: "{{ docker_user_root_dir }}/grafana"

grafana_image_base: "grafana/grafana"
grafana_container_name: "grafana"

grafana_backup_directory: "/mnt/backup/"
grafana_nfs_backup_directory: "/nfs/Container-Data/docker/grafana/"
# Defines in days age of backups to remove
grafana_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
grafana_nfs_backup_frequency: "0 1 */15 * *"

grafana_envs:
  kv:
