docker_data_dir: "{{ docker_user_root_dir }}/pihole/"
docker_data_dir_sub_folders:
  - "etc-pihole/"
  - "etc-dnsmasq.d/"
  - "etc-pihole-updatelists/"

pihole_image_base: "pihole/pihole"
pihole_image_base_tag: "v5.8.1"
pihole_container_name: "pihole"
pihole_image_custom: "{{ ansible_user }}/pihole"

pihole_envs:
  kv:
    TZ: "America/Vancouver"
    WEBPASSWORD: "{{ docker_services_admin_password }}"
    WEB_PORT: "8080"
  PIHOLE_DNS_:
    - 192.168.1.201
    - 1.1.1.1
    - 8.8.8.8

pihole_networks:
  - "{{ docker_networks.proxy.name }}"

pihole_container_volumes:
  binds:
    - source: "./etc-pihole/"
      target: "/etc/pihole/"
    - source: "./etc-dnsmasq.d/"
      target: "/etc/dnsmasq.d/"
    - source: "./etc-pihole-updatelists/"
      target: "/etc/pihole-updatelists/"
  volumes:
    - type: "volume"
      source: "{{ pihole_volumes.nfs_vol.name }}"
      target: "/nfs/backup"

pihole_volumes:
  nfs_vol:
    name: "nfs_vol"
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr={{ nfs_server_ipv4_address }},rw,nolock,soft"
      device: ":/Container-Data/docker/pihole"
