pihole_container_data_dir: "{{ docker_container_root_dir }}/pihole"

pihole_image_base: "pihole/pihole"
pihole_image_base_tag: ""
# Ensures previous version of working
# pihole image is available for failback
pihole_image_base_tag_old: ""
pihole_container_name: "pihole"
# Controls whether docker-compose restarts Docker containers
pihole_container_restart: no
pihole_image_custom: "{{ ansible_user }}/pihole"

pihole_external_ip_mapping: "{{ home_lan_dns_servers[0] }}"

pihole_backup_directory: "/mnt/backup/"
pihole_nfs_backup_directory: "/nfs/Container-Data/docker/pihole/teleport"
# Defines in days age of backups to remove
pihole_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
pihole_nfs_backup_frequency: "0 1 */15 * *"

pihole_container_envs:
  kv:
    TZ: "America/Vancouver"
    WEBPASSWORD: "{{ docker_services_admin_password }}"
    WEB_PORT: "{{ services_pihole_web_port }}"
  PIHOLE_DNS_:
    - 1.1.1.1
    - 8.8.8.8
