ddclient_version: "3.9.1"
ddclient_url: "https://github.com/ddclient/ddclient/archive/refs/tags/v{{ ddclient_version }}.tar.gz"

ddclient_daemon: "600"
ddclient_protocol: "cloudflare"
ddclient_server: "api.cloudflare.com/client/v4"
