---
### Prometheus AlertManager discovery
prometheus_alerting_alertmanagers:
  - timeout: ""
    path_prefix: ""
    scheme: ""
    static_configs:
      targets:
        - hosts:
            - hostname: "alertmanager"
              port: "9093"

### AlertManager

# Default receiver
alertmanager_route_default_receiver: "default-receiver"
alertmanager_route_default_group_wait: "30s"
alertmanager_route_default_group_interval: "5m"
alertmanager_route_default_repeat_interval: "4h"

# List of notification receivers
alertmanager_receivers:
  - name: "default-receiver"
    email_configs:
      send_resolved: "true"
      to: "monitoring.notifications@m.{{ home_lan_domain_public}}"
      from: "monitoring.notifications@m.{{ home_lan_domain_public }}"
      smarthost: "{{ smtp_monitoring_server_url }}"
      hello: ""
      auth_username: "apikey"
      auth_password: "{{ smtp_monitoring_api_key }}"
      auth_secret: ""
      auth_identity: ""
      require_tls: "false"

### Alerting rules

prometheus_rule_files:
  - "alert.rules"
