---

### Issue #675
# One of the MIBS aren't being downloaded
# Fixed in Commit 4307bba
# Not included in v0.20.0 tag
# Switch to version tag when included
- name: "TASK: Clone SNMP exporter repo"
  git:
    repo: "https://github.com/prometheus/snmp_exporter.git"
    dest: "{{ docker_data_dir }}/temp"
    single_branch: yes
    # version: "{{ image_base_tag }}"
    version: "main"
    force: yes

- name: "TASK: Make SNMP Generator MIBS"
  community.general.make:
    chdir: "{{ docker_data_dir }}/temp/generator"
    target: "mibs"

- name: "TASK: Add custom MIBS to mibs directory"
  copy:
    src: "{{ item }}"
    dest: "{{ docker_data_dir }}/temp/generator/mibs"
    mode: 0664
    force: yes
  with_fileglob:
    - "mibs/*"
  loop_control:
    label: "{{ item | basename }}"

- name: "TASK: Build snmp-generator binary"
  shell:
    cmd: "go build"
  args:
      chdir: "{{ docker_data_dir }}/temp/generator"

- name: "TASK: Add generator.yml entries"
  blockinfile:
    path: "{{ docker_data_dir }}/temp/generator/generator.yml"
    block: "{{ lookup('template', 'generator.yml.j2')}}"
    insertafter: "EOF"
    mode: 0664
    state: "present"

- name: "TASK: Generate snmp.yml"
  shell:
    cmd: "./generator generate"
  args:
      chdir: "{{ docker_data_dir }}/temp/generator"
  environment:
    MIBDIRS: "mibs"

- name: "TASK: Move snmp.yml out of temp folder"
  copy:
    src: "{{ docker_data_dir }}/temp/generator/snmp.yml"
    remote_src: yes
    dest: "{{ docker_data_dir }}/snmp_generator"
    mode: 0664
