docker_data_dir: "{{ docker_user_root_dir }}/traefik"

wireguard_image_base: "traefik"
wireguard_container_name: "traefik"

wireguard_backup_directory: "/mnt/backup/"
wireguard_nfs_backup_directory: "/nfs/Container-Data/docker/traefik/"
# Defines via cron syntax how often to run backup
wireguard_nfs_backup_frequency: "0 1 */30 * *"

traefik_envs:
  kv:
