---
- name: "Create root folder for container"
  become: true
  file:
    path: "{{ ryot_media_container_data_dir }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"

- name: "Create folders for build and container data"
  become: true
  file:
    path: "{{ ryot_media_container_data_dir }}/{{ item }}"
    owner: "{{ ryot_media_pid }}"
    group: "{{ ryot_media_gid }}"
    mode: 0775
    state: "directory"
  with_items: "{{ ryot_media_container_data_dir_sub_folders }}"

- name: "Create folders for build and container db data"
  become: true
  file:
    path: "{{ ryot_media_container_data_dir }}/{{ item }}"
    owner: "{{ ryot_media_db_pid }}"
    group: "{{ ryot_media_db_gid }}"
    mode: 0700
    state: "directory"
  with_items: "{{ ryot_media_db_container_data_dir_sub_folders }}"

- name: "Template files for building and running {{ ryot_media_container_name }}"
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ryot_media_pid }}"
    group: "docker"
    mode: 0660
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ ryot_media_container_data_dir }}/docker-compose.yml"
    - src: "ryot_media.env.j2"
      dest: "{{ ryot_media_container_data_dir }}/ryot_media.env"
    - src: "ryot_media_db.env.j2"
      dest: "{{ ryot_media_container_data_dir }}/ryot_media_db.env"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "Template files for building and running {{ ryot_media_container_name }}"
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ryot_media_pid }}"
    group: "{{ ryot_media_gid }}"
    mode: 0660
  with_items:
    - src: "ryot_config.yaml.j2"
      dest: "{{ ryot_media_container_data_dir }}/ryot_config/ryot.yaml"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "TASK: Set containers to restart when templated files change"
  set_fact:
    ryot_media_container_restart: "yes"
  when: "container_templated_files.changed"
