alertManager_container_data_dir: "{{ docker_container_root_dir }}/alertManager"

alertManager_image_base: "alertManager/alertManager"
alertManager_image_base_tag: ""
# Ensures previous version of working
# alertManager image is available for failback
alertManager_image_base_tag_old: ""
alertManager_container_name: "alertManager"
# Controls whether docker-compose restarts Docker containers
alertManager_container_restart: no
# Defines image ID for custom image
alertManager_image_custom: "{{ ansible_user }}/alertManager"

alertManager_backup_directory: "/mnt/backup/"
alertManager_nfs_backup_directory: "/nfs/Container-Data/docker/SERVICE/"
# Defines in days age of backups to remove
alertManager_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
alertManager_nfs_backup_frequency: "0 1 */15 * *"

alertManager_container_envs:
  kv:
