alertmanager_container_data_dir: "{{ docker_container_root_dir }}/alertmanager"

alertmanager_image_base: "prom/alertmanager"
alertmanager_image_base_tag: ""
# Ensures previous version of working
# alertmanager image is available for failback
alertmanager_image_base_tag_old: ""
alertmanager_container_name: "alertmanager"
# Controls whether docker-compose restarts Docker containers
alertmanager_container_restart: no
# Defines image ID for custom image

alertmanager_docker_cli_commands:
  "config.file": "/etc/alertmanager/alertmanager.yml"

alertmanager_container_envs:
  kv:

alertmanager_global_smtp_from: ""
alertmanager_global_smtp_smarthost: ""
alertmanager_global_smtp_hello: "localhost"
alertmanager_global_smtp_auth_username: ""
alertmanager_global_smtp_auth_password: ""
alertmanager_smtp_auth_identity: ""
alertmanager_smtp_auth_secret: ""
alertmanager_global_smtp_require_tls: "true"

alertmanager_global_resolve_timeout: "5m"
