---
# configure-qnap-le-ssl

ssl_path: "/share/Public/ssl"
cert_path: "{{ ssl_path }}/certificates"

# Indicates version of LEgo to install
lego_version: "4.9.1"
lego_version_previous: ""
lego_install_url: "https://github.com/go-acme/lego/releases/download/v{{ lego_version }}/lego_v{{ lego_version }}_linux_armv7.tar.gz"

lego_installation_dir: "/share/CACHEDEV1_DATA/.qpkg/LEgo"

# List of domains to request for LE certificates
lego_domains:
  - "nas1.{{ home_lan_domain }}"

# Cron interval to refresh LE certificate
lego_refresh_interval: "0 3 * * 6"
# Threshold in days for when LE certs should be renewed
lego_cert_renewal_period: 30

cf_api_email: "lets.encrypt.certs@m.{{ home_lan_domain_public }}"
cf_dns_api_token: "{{ dns_provider_api_token_letsencrypt }}"
