frigate_container_data_dir: "{{ docker_container_root_dir }}/frigate"

frigate_image_base: "ghcr.io/blakeblackshear/frigate"
frigate_image_base_tag: ""
# Ensures previous version of working
# frigate image is available for failback
frigate_image_base_tag_old: ""
frigate_container_name: "frigate"
# Controls whether docker-compose restarts Docker containers
frigate_container_restart: no
# Defines image ID for custom image
frigate_image_custom: "{{ ansible_user }}/frigate"

# Ports
frigate_port_web: 5000
frigate_port_rtsp: 8554
frigate_port_webrtc: 8555

frigate_container_envs:
  kv:
    "FRIGATE_RTSP_PASSWORD": "{{ frigate_rtsp_password }}"
