docker_data_dir_sub_folders:
  - "var-lib-grafana/"
  - "mnt-backup/"
  - "scripts"

grafana_container_volumes:
  binds:
    - source: "./var-lib-grafana/"
      target: "/var/lib/grafana/"
    - source: "./mnt-backup/"
      target: "/mnt/backup/"
