---

- name: "TASK: Install authorized SSH keys"
  ansible.posix.authorized_key:
    exclusive: yes
    comment: "Ansible managed key"
    user: "{{ ansible_user }}"
    state: "present"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "ssh_keys/*"

- name: "TASK: Configure SSHD"
  become: true
  template:
    src: sshd.conf.j2
    dest: /etc/ssh/sshd_config.d/10-ansible-sshd.conf
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
  - "restart sshd"
