---
- name: "TASK: Ensure mosquitto packages are installed"
  include_role:
    name: install-system-packages
  vars:
    packages_to_install:
      - mosquitto

- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ mqtt_mosquitto_container_name }}"
  register: container_state

- name: "TASK: Set container facts"
  set_fact:
    container_exists: "{{ container_state.exists }}"
    container_image: "{{ container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    container_image_tag: "{{ container_image.split(':') }}"

- block:
    - include_tasks: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ mqtt_mosquitto_image_base }}"
        tag: "{{ mqtt_mosquitto_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "image_base_pull"
  when: container_image_tag[1] != mqtt_mosquitto_image_base_tag

- block:
    - include_tasks: "deploy_authentication.yml"
  when: "mqtt_mosquitto_auth_enable == 'true'"

- name: "TASK: Delete {{ mqtt_mosquitto_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ mqtt_mosquitto_container_data_dir }}"
    state: "absent"
  when: image_base_pull.changed or container_templated_files.changed
  register: container_deleted

- name: "TASK: Deploy {{ mqtt_mosquitto_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ mqtt_mosquitto_container_data_dir }}"
    state: "{{ 'restarted' if mqtt_mosquitto_container_restart and not container_deleted.changed else 'present' }}"
