---
- name: "TASK: Ensure mosquitto packages are installed"
  include_role:
    name: install-system-packages
  vars:
    packages_to_install:
      - mosquitto

- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ mqtt_mosquitto_container_name }}"
  register: container_state

- name: "TASK: Set container facts"
  set_fact:
    container_exists: "{{ container_state.exists }}"
    container_image: "{{ container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    container_image_tag: "{{ container_image.split(':') }}"

- block:
    - include_tasks: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ mqtt_mosquitto_image_base }}"
        tag: "{{ mqtt_mosquitto_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "image_base_pull"

    - name: "TASK: Remove container for updates"
      community.docker.docker_container:
        name: "{{ mqtt_mosquitto_container_name }}"
        container_default_behavior: "no_defaults"
        state: "absent"
      when: container_exists and image_base_pull.changed
  when: container_image_tag[1] != mqtt_mosquitto_image_base_tag

- block:
    - include_tasks: "deploy_authentication.yml"
  when: "mqtt_mosquitto_auth_refresh and mqtt_mosquitto_auth_enable == 'true'"

- name: "TASK: Deploy {{ mqtt_mosquitto_container_name }}"
  community.docker.docker_compose:
    project_src: "{{ mqtt_mosquitto_container_data_dir }}"
    nocache: "no"
    state: "present"
    restarted: "{{ mqtt_mosquitto_container_restart }}"
