---
- name: "TASK: Verify backup directory"
  stat:
    path: "{{ mqtt-mosquitto_nfs_backup_directory }}"
  register: stat_backup_dir

- name: "TASK: Assert backup directory exists"
  assert:
    that:
      - stat_backup_dir.stat.isdir is defined
      - stat_backup_dir.stat.isdir
    fail_msg: "Backup directory doesn't exist"
    success_msg: "Backup directory exists"

- name: "TASK: Create {{ mqtt-mosquitto_container_name }} backup cron job"
  become: true
  template:
    src: mqtt-mosquitto-backup.j2
    dest: "/etc/cron.d/mqtt-mosquitto-backup"
    owner: root
    group: root
    mode: 0644

- name: "TASK: Create {{ mqtt-mosquitto_container_name }} backup script"
  become: true
  template:
    src: "mqtt-mosquitto-backup.sh.j2"
    dest: "{{ mqtt-mosquitto_container_data_dir }}/scripts/mqtt-mosquitto-backup.sh"
    owner: root
    group: root
    mode: 0755
