---
- name: "Create root folder for container"
  become: true
  file:
    path: "{{ mqtt_mosquitto_container_data_dir }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"

- name: "Create folders for build and container data"
  become: true
  file:
    path: "{{ mqtt_mosquitto_container_data_dir }}/{{ item }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"
  with_items: "{{ mqtt_mosquitto_container_data_dir_sub_folders }}"

- name: "Template files for building and running {{ mqtt_mosquitto_container_name }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "docker"
    mode: 0660
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ mqtt_mosquitto_container_data_dir }}/docker-compose.yml"
    - src: "mqtt_mosquitto.env.j2"
      dest: "{{ mqtt_mosquitto_container_data_dir }}/mqtt_mosquitto.env"
    - src: "mosquitto.conf.j2"
      dest: "{{ mqtt_mosquitto_container_data_dir }}/config/mosquitto.conf"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "TASK: Set containers to restart when templated files change"
  set_fact:
    container_restart: "yes"
  when: "container_templated_files.changed"
