---
- name: "TASK: Download k3s binary (x64)"
  get_url:
    url: "{{ k3s_binary_url }}/{{ k3s_version_to_install }}/k3s"
    checksum: "sha256:{{ k3s_binary_url }}/{{ k3s_version_to_install }}/sha256sum-amd64.txt"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
