---

- name: Baseline setup
  hosts: all
  ### Executing locally for testing
  # hosts: localhost
  # connection: local
  gather_facts: true

  roles:
    - create-directories
    - install-system-packages
    - configure-host-file
    - configure-ssh
    - configure-ubuntu-settings
    - install-snap-packages
    - install-pip-packages
    - install-docker-ce
    - install-hashicorp-vault
    - create-symlinks
    - update-homeConfig-files
    - configure-users
