system_packages:
- autofs
- fail2ban
- net-tools

fail2ban_ignoreip:
- "192.168.1.0/24"

docker_networks:
  proxy:
    name: "proxy"
    driver: "bridge"
    enable_ipv6: "false"
    scope: "local"
    internal: "false"
    external: "true"
    state: "present"

docker_user_root_dir: "/home/{{ ansible_user }}/docker"

ufw_rules:
- comment: "Permits incoming SSH connections"
  rule: allow
  delete: no
  from_ip: any
  to_ip: any
  from_port: null
  to_port: '22'
  proto: tcp
- comment: "Permits incoming HTTP connections"
  rule: allow
  delete: no
  from_ip: any
  to_ip: any
  from_port: null
  to_port: '80'
  proto: tcp
- comment: "Permits incoming HTTPS connections"
  rule: allow
  delete: no
  from_ip: any
  to_ip: any
  from_port: null
  to_port: '443'
  proto: tcp
