---

- name: "TASK: Template netplan config"
  become: true
  template:
    src: "60-netcfg.yml.j2"
    dest: "/etc/netplan/"
    owner: root
    group: root
    mode: 0644
  notify:
    - "apply netplan"
