docker_data_dir_sub_folders:
  - "configurations"
  - "letsEncrypt"

traefik_image_base_tag: "v2.4.8"
# Ensures previous version of working
# traefik image is available for failback
traefik_image_base_tag_old: ""

traefik_container_volumes:
  binds:
    - source: "/var/run/docker.sock"
      target: "/var/run/docker.sock:ro"
    - source: "./traefik.yml"
      target: "/traefik.yml:ro"
    - source: "./configurations"
      target: "/configurations"
    - source: "./letsEncrypt"
      target: "/letsEncrypt/"
