traefik_container_data_dir_sub_folders:
  - "configurations"
  - "letsEncrypt"

traefik_container_volumes:
  binds:
    - source: "/var/run/docker.sock"
      target: "/var/run/docker.sock:ro"
    - source: "./traefik.yml"
      target: "/traefik.yml:ro"
    - source: "./configurations"
      target: "/configurations"
    - source: "./letsEncrypt"
      target: "/letsEncrypt/"
    - source: "{{ traefik_logging_directory }}"
      target: "{{ traefik_logging_directory }}"
