---
- name: "TASK: Store master node IP address"
  set_fact:
    k3s_master_node_ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"

- name: "TASK: Copy K3s service file"
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0644

- name: "TASK: Enable and check K3s service"
  systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

- name: "TASK: Wait for node-token"
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: "TASK: Register node-token file access mode"
  stat:
    path: /var/lib/rancher/k3s/server
  register: original_node_token_access_mode

- name: "TASK: Change file access node-token"
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: "TASK: Read node-token from master"
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: "TASK: Store Master node-token"
  set_fact:
    k3s_master_node_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: "TASK: Restore node-token file access"
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ original_node_token_access_mode.stat.mode }}"

- name: "TASK: Create directory .kube"
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: "TASK: Change k3s.yaml permissions to 644"
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: "{{ ansible_user }}"
    mode: "644"

- name: "TASK: Replace https://localhost:6443 by https://master-ip:6443"
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ k3s_master_node_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: "TASK: Create kubectl symlink"
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: "TASK: Create crictl symlink"
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
