---
# configure-plover tasks

- name: "TASK: Create Plover config directory"
  file:
    name: "{{ ansible_env.HOME }}/.config/plover/"
    state: directory

- name: "TASK: Template Plover settings file"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/plover/{{ item }}"
    mode: 0644
    backup: yes
  with_items:
    - "commands.json"
    - "main.json"
    - "plover.cfg"
    - "user.json"
