---

- name: "TASK: Create .ssh directory"
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0755

- name: "TASK: Create SSH config"
  template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0600
