---
- name: "TASK: Set the system timezone"
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone_tz_identifier }}"
    dest: "/etc/localtime"
    owner: "root"
    group: "root"
    state: link
