portainer_container_data_dir: "{{ docker_container_root_dir }}/portainer"

portainer_image_base: "REPO/portainer"
portainer_image_base_tag: ""
# Ensures previous version of working
# portainer image is available for failback
portainer_image_base_tag_old: ""
portainer_container_name: "portainer"
# Controls whether docker-compose restarts Docker containers
portainer_container_restart: no
# Defines image ID for custom image
portainer_image_custom: "{{ ansible_user }}/portainer"

portainer_backup_directory: "/mnt/backup/"
portainer_nfs_backup_directory: "/nfs/Container-Data/docker/SERVICE/"
# Defines in days age of backups to remove
portainer_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
portainer_nfs_backup_frequency: "0 1 */15 * *"

portainer_container_envs:
  kv:
