---
# Port definitions for various services
pihole_container_web_port: "80"
grafana_container_web_port: "3000"
snmp_exporter_container_web_port: "9116"

# Home Internet Monitoring
home_internet_blackbox_exporter_container_port: "9115"
home_internet_speedtest_exporter_container_port: "9798"

# ddclient
ddclient_version: "3.10.0"

# MQTT
mqtt_mosquitto_auth_credentials: "{{ vault_mqtt_mosquitto_auth_credentials }}"

# Frigate
frigate_rtsp_password: "{{ vault_frigate_rtsp_password }}"

# Z-Wave JS Server
zwave_js_ui_websocket_server_port: "3001"

# Media Management Credentials
media_management_user_username: "{{ vault_media_management_user_username }}"
media_management_user_password: "{{ vault_media_management_user_password }}"
