paperless_ngx_container_data_dir_sub_folders:
  - "paperless_consume"
  - "paperless_media"
  - "scripts"

# Directories of differing permissions
paperless_ngx_custom_perms_container_data_dir_sub_folders:
  paperless_data:
    owner: "{{ paperless_ngx_uid }}"
    group: "{{ paperless_ngx_uid }}"
    mode: "0775"
  paperless_export:
    owner: "{{ paperless_ngx_uid }}"
    group: "{{ paperless_ngx_uid }}"
    mode: "0775"
  paperless_postgres:
    owner: "70"
    group: "999"
    mode: "0700"
  paperless_redis:
    owner: "999"
    group: "999"
    mode: "0775"

paperless_ngx_redis_container_volumes:
  binds:
    - source: "./paperless_redis/"
      target: "/data/"

paperless_ngx_postgres_container_volumes:
  binds:
    - source: "./paperless_postgres/"
      target: "/var/lib/postgresql/data/"
