---
docker_data_root_dir: "/mnt/docker-data/var/lib/docker"
### Rename to container data
docker_user_root_dir: "/mnt/docker-data/container-data"

# Used for any admin console on deployed Docker services
docker_services_admin_username: "{{ vault_docker_services_admin_username }}"
docker_services_admin_password: "{{ vault_docker_services_admin_password }}"

docker_repo_filename: "docker"
docker_repo_type: "stable"

docker_daemon_config:
  - data-root: "{{ docker_data_root_dir }}"

docker_networks:
  proxy:
    name: "proxy"
    driver: "bridge"
    enable_ipv6: "false"
    scope: "local"
    internal: "false"
    external: "true"
    state: "present"
  monitoring:
    name: "monitoring"
    driver: "bridge"
    enable_ipv6: "false"
    scope: "local"
    internal: "false"
    external: "true"
    state: "present"
