---
- name: "TASK: Store master node IP address"
  set_fact:
    k3s_master_node_ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"

- name: "TASK: Copy config to local host"
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: true
