---

# Copies cron to host to execute teleport -a -t in container
# Will also create cron job that rsyncs backup data to autofs NFS server location

- name: "TASK: Create {{ smtp_relay_container_name }} teleport backup directory"
  become: true
  file:
    path: "{{ smtp_relay_nfs_backup_directory }}"
    state: "directory"

- name: "TASK: Create {{ smtp_relay_container_name }} backup cron job"
  become: true
  template:
    src: smtp_relay-backup.j2
    dest: "/etc/cron.d/smtp_relay-backup"
    owner: root
    group: root
    mode: 0644

- name: "TASK: Create {{ smtp_relay_container_name }} backup script"
  become: true
  template:
    src: "smtp_relay-backup.sh.j2"
    dest: "{{ docker_data_dir }}/scripts/smtp_relay-backup.sh"
    owner: root
    group: root
    mode: 0755
