---

- name: "Template files for building and running {{ pihole_container_name }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "docker"
    mode: 0660
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ docker_data_dir }}/docker-compose.yml"
    - src: "smtp_relay.env.j2"
      dest: "{{ docker_data_dir }}/smtp_relay.env"
  loop_control:
    label: "{{ item.src }}"
