snmp_exporter_container_data_dir: "{{ docker_container_root_dir }}/snmp_exporter"

snmp_exporter_image_base: "prom/snmp-exporter"
snmp_exporter_image_base_tag: ""
# Ensures previous version of working
# snmp_exporter image is available for failback
snmp_exporter_image_base_tag_old: ""
snmp_exporter_container_name: "snmp_exporter"
snmp_exporter_container_web_port: "9116"
# Controls whether docker-compose restarts Docker containers
snmp_exporter_container_restart: no

snmp_exporter_container_envs:
  kv:

snmp_exporter_docker_cli_commands:
  "config.file": "/etc/snmp_exporter/snmp.yml"
  "web.listen-address": ":{{ snmp_exporter_container_web_port }}"

snmp_community_strings:
  public_v2:
    community: "public"
    version: 2

snmp_exporter_prometheus_mib_modules:
  - name: ""
    walk:
      - ""
    version: ""
    max_repetitions: ""
    retries: ""
    timeout: ""
    auth:
      community: ""
      username: ""
      security_level: ""
      password: ""
      auth_protocol: ""
      priv_protocol: ""
      priv_password: ""
      context_name: ""
    lookups:
      - source_indexes: []
        lookup: ""
        drop_source_indexes: ""
    overrides:
      - metric_name: ""
        type: ""
