---

- name: "TASK: Create {{ grafana_container_name }} backup cron job"
  become: true
  template:
    src: grafana-backup.j2
    dest: "/etc/cron.d/grafana-backup"
    owner: root
    group: root
    mode: 0644

- name: "TASK: Create {{ grafana_container_name }} backup script"
  become: true
  template:
    src: "grafana-backup.sh.j2"
    dest: "{{ docker_data_dir }}/scripts/grafana-backup.sh"
    owner: root
    group: root
    mode: 0755
