---

- name: "PLAY: Baselining servers"
  hosts: rbp4-001
  gather_facts: true

  roles:
    - role: install-system-packages
      tags: [ baseline ]
    - role: configure-hostname
      tags: [ baseline ]
    - role: configure-systemd-resolved
      tags: [ baseline, refresh, network ]
    - role: configure-cloud-init
      tags: [ baseline, refresh, network ]
    - role: configure-ssh-server
      tags: [ baseline, refresh, security ]
    - role: configure-ufw
      tags: [ baseline, refresh, security ]
    - role: configure-fail2ban
      tags: [ baseline, refresh, security ]
    - role: configure-autofs
      tags: [ baseline, refresh ]
    - role: configure-docker
      tags: [ baseline, refresh ]

- name: "PLAY: Deploy services"
  hosts: rbp4-001
  gather_facts: true

  roles:
    - role: deploy-pihole
      tags: [ services ]
