---

- name: "PLAY: Deploy services"
  hosts: rbp4-001
  gather_facts: true

  roles:
    - role: deploy-pihole
      tags: [ services, pihole ]
    - role: configure-ddclient
      tags: [ services, vpn, ddclient ]
    - role: deploy-wireguard
      tags: [ services, vpn, wireguard ]
    - role: deploy-traefik
      tags: [ services, proxy, traefik ]
    - role: deploy-smtp-relay
      tags: [ services, smtp_relay ]
    - role: deploy-grafana
      tags: [ services, grafana]
    - role: deploy-prometheus
      tags: [ services, prometheus ]
