automation_pip_packages:
  - gns3-server
  - gns3-gui
  - pyqt5

system_pip_packages:
  # Language linting
  - ansible-lint
  - pylint
  - black
  # ProtonVPN
  - protonvpn-cli

system_users: "{{ vault_system_users }}"

# Family NAS
smb_username: "{{ vault_smb_username }}"
smb_password: "{{ vault_smb_password }}"
smb_domain: "{{ vault_smb_domain }}"
home_domain: "{{ vault_home_domain }}"
family_nas_hostname: "{{ vault_family_nas_hostname }}"
family_nas_FQDN: "{{ family_nas_hostname }}.{{ home_domain }}"

home_printer_fqdn: "printer.{{ home_domain }}"

# Github
github_access_token: "{{ vault_github_access_token }}"

ssh_config_hosts: "{{ vault_ssh_config_hosts }}"
