---

- name: "Create root folder for container"
  become: true
  file:
    path: "{{ alertmanager_container_data_dir }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"

- name: "Create folders for build and container data"
  become: true
  file:
    path: "{{ alertmanager_container_data_dir }}/{{ item }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"
  with_items: "{{ alertmanager_container_data_dir_sub_folders }}"

- name: "Template files for building and running {{ alertmanager_container_name }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "docker"
    mode: 0660
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ alertmanager_container_data_dir }}/docker-compose.yml"
    - src: "alertmanager.env.j2"
      dest: "{{ alertmanager_container_data_dir }}/alertmanager.env"
    - src: "alertmanager.yml.j2"
      dest: "{{ alertmanager_container_data_dir }}/etc-alertmanager/alertmanager.yml"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "TASK: Template {{ alertmanager_container_name }} config files"
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    # Maps to UID that's in alertmanager container
    owner: "65534"
    group: "docker"
    mode: 0660
  with_items:
    - src: "alertmanager.yml.j2"
      dest: "{{ alertmanager_container_data_dir }}/etc-alertmanager/alertmanager.yml"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "TASK: Set containers to restart when templated files change"
  set_fact:
    container_restart: "yes"
  when: "container_templated_files.changed"
