---
ansible_host: "{{ inventory_hostname }}.{{ home_lan_domain }}"
ansible_user: "{{ vault_ansible_user }}"
ansible_become_password: "{{ vault_ansible_become_password }}"

# Converts Ansible detected architectures to commonly used ones
cpu_architecture_mappings:
  "x86_64": "amd64"
  "aarch64": "arm64"

timezone_tz_identifier: "America/Vancouver"

nfs_server_ipv4_address: "{{ vault_nfs_server_ipv4_address }}"
autofs_nfs_shares: "{{ vault_autofs_nfs_shares }}"

local_users: "{{ vault_local_users }}"

home_lan_domain_public: "{{ vault_home_lan_domain_public }}"
home_lan_domain: "{{ vault_home_lan_domain }}"
home_lan_cidr: "{{ vault_home_lan_cidr }}"
home_lan_gateway: "{{ vault_home_lan_gateway }}"
home_lan_dns_servers: "{{ vault_home_lan_dns_servers }}"

home_vpn_cidr: "{{ vault_home_vpn_cidr }}"
home_vpn_server_external_url: "wg.{{ home_lan_domain_public }}"
# List of Wireguard peers to create
home_vpn_peers: "{{ vault_home_vpn_peers }}"

home_smtp_relay_server: "smtp.sendgrid.net"
home_smtp_relay_server_username: "apikey"
home_smtp_relay_server_api_key: "{{ vault_home_smtp_relay_server_api_key }}"
home_smtp_relay_server_hostname: "{{ home_lan_domain_public }}"
home_smtp_relay_server_authenticated_sender: "{{ vault_home_smtp_relay_server_authenticated_sender }}"

dns_provider_ddns_domains_to_update: "{{ vault_dns_provider_ddns_domains_to_update }}"
dns_provider_api_token: "{{ vault_dns_provider_api_token }}"
dns_provider_api_token_letsencrypt: "{{ vault_dns_provider_api_token_letsencrypt }}"

home_backup_cifs_username: "{{ vault_home_backup_cifs_username }}"
home_backup_cifs_password: "{{ vault_home_backup_cifs_password }}"

# Monitoring

### Node_Exporter
prometheus_node_exporter_version: "1.2.2"
