---
- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ immich_server_container_name }}"
  register: container_state

- name: "TASK: Set container facts"
  set_fact:
    container_exists: "{{ container_state.exists }}"
    container_image: "{{ container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    container_image_tag: "{{ container_image.split(':') }}"

- block:
    - include_tasks: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ immich_server_image_base }}"
        tag: "{{ immich_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "image_base_pull"
  when: container_image_tag[1] != immich_image_base_tag

- name: "TASK: Delete Immich"
  community.docker.docker_compose_v2:
    project_src: "{{ immich_container_data_dir }}"
    state: "absent"
  when: image_base_pull.changed or container_templated_files.changed

- name: "TASK: Deploy Immich"
  community.docker.docker_compose_v2:
    project_src: "{{ immich_container_data_dir }}"
    state: "{{ 'restarted' if immich_container_restart else 'present' }}"
