---

- name: "TASK: Configure base logrotate config"
  become: true
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    backup: true
    owner: root
    group: root
    mode: 0644
  when: logrotate_custom_app.name is none

- name: "TASK: Configure app-specific logrotate config"
  become: true
  template:
    src: "logrotate_app.j2"
    dest: "/etc/logrotate.d/logrotate-{{ logrotate_custom_app.name }}"
    owner: root
    group: root
    mode: 0644
  when: logrotate_custom_app.name is not none
