---
# Container config
frigate_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.frigate1.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`)"
  - "traefik.http.routers.frigate1.entrypoints=websecure"
  - "traefik.http.routers.frigate1.middlewares=secureHeaders@file,authelia"
  - "traefik.http.routers.frigate1.service=frigate-svc"
  - "traefik.http.services.frigate-svc.loadbalancer.server.port={{ frigate_port_web }}"
  - "traefik.http.routers.frigate1.tls=true"
  - "traefik.http.routers.frigate1.tls.certresolver=letsEncrypt"

frigate_use_custom_go2rtc: true
frigate_custom_go2rtc_version: "1.6.2"

# Frigate configuration
frigate_mqtt_enabled: True
# Frigate MQTT Host is name of MQTT container running on the same host
# Only defined like this since communication through traefik doesn't
# work over SSL
frigate_mqtt_host: "mqtt_mosquitto"
frigate_mqtt_port: "{{ mqtt_mosquitto_port_tcp }}"
frigate_mqtt_user: "{{ mqtt_mosquitto_auth_credentials[0].username }}"
frigate_mqtt_password: "{{ mqtt_mosquitto_auth_credentials[0].password }}"

frigate_go2rtc:
  streams:
    front_door:
      - "rtsp://home-assistant-001.{{ home_lan_domain }}:8556/front-door"
      - "ffmpeg:front_door#audio=opus"
    front_door_substream:
      - "rtsp://home-assistant-001.{{ home_lan_domain }}:8556/front-door-sub"
    front_door_bell:
      # - "rtsp://{{ reolink_cameras_username }}:{{ reolink_cameras_password }}@doorbell-front.{{ home_lan_domain }}:554/h264Preview_01_main"
      # - "ffmpeg:front_door_bell#audio=pcm"
      - "http://doorbell-front.{{ home_lan_domain }}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={{ reolink_cameras_username }}&password={{ reolink_cameras_password }}"
      - "ffmpeg:front_door_bell#audio=opus"
    front_door_bell_substream:
      # - "rtsp://{{ reolink_cameras_username }}:{{ reolink_cameras_password }}@doorbell-front.{{ home_lan_domain }}:554/h264Preview_01_sub"
      - "http://doorbell-front.{{ home_lan_domain }}/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={{ reolink_cameras_username }}&password={{ reolink_cameras_password }}"
    garage:
      - "rtsp://home-assistant-001.{{ home_lan_domain }}:8556/rear-driveway"
      - "ffmpeg:front_door#audio=opus"
    garage_substream:
      - "rtsp://home-assistant-001.{{ home_lan_domain }}:8556/rear-driveway-sub"
  # Necessary for establishing webrtc connection via live view
  webrtc:
    candidates:
      - frigate-001.{{ home_lan_domain }}:8555
      - stun:8555

frigate_cameras:
  front_door_bell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door_bell" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_door_bell_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 7
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        required_zones:
          - front_yard_left
          - front_yard_right
          - front_yard_walkway
        retain:
          default: 20
          mode: motion
          objects:
            person: 30
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
      required_zones:
        - front_yard_left
        - front_yard_right
        - front_yard_walkway
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask:
            - 0,0,470,0,496,66,518,205,501,205,450,205,435,196,398,181,364,212,77,207,69,192,53,176,23,177,0,203
    zones:
      front_yard_left:
        coordinates: 162,258,40,255,80,187,27,167,0,200,0,253,0,480,121,480,246,480
        objects:
          - person
          - cat
          - dog
      front_yard_right:
        coordinates: 217,255,378,247,382,198,411,189,513,200,510,253,503,303,487,373,427,389,354,392,301,341,232,279
        objects:
          - person
          - cat
          - dog
      front_yard_walkway:
        coordinates: 640,480,640,108,501,118,501,325,427,371,348,382,222,266,168,267,222,407,0,412,0,480
        objects:
          - person
    motion:
      improve_contrast: True
      mask:
        - 0,0,470,0,496,66,518,205,501,205,450,205,435,196,398,181,364,212,77,207,69,192,53,176,23,177,0,203
        - 368,451,640,447,640,480,371,480
    live:
      stream_name: "front_door_bell"
  front_door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_door_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        required_zones:
          - front_yard
          - front_yard_street
        retain:
          default: 20
          mode: motion
          objects:
            person: 30
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          mask:
            - 633,266,631,224,588,209,542,215,556,264
            - 608,0,1280,0,1280,156,1136,129,825,87,286,97,90,201,0,163,0,0
    zones:
      front_yard:
        coordinates: 1280,720,1280,300,1280,143,1175,130,1181,185,1159,266,822,247,529,253,257,269,144,276,0,296,0,720
        objects:
          - person
          - cat
          - dog
      front_yard_street:
        coordinates: 674,249,944,264,1163,257,1176,172,1280,153,1280,0,976,0,739,0,0,0,0,287,246,260
        objects:
          - person
    motion:
      mask:
        - 1280,720,1280,384,1237,370,1163,394,1120,457,1124,543,1125,665,1156,720
        - 608,0,1280,0,1280,140,1229,90,1131,111,825,87,260,79,90,201,0,163,0,0
    ### Masks, filters for original camera orientation with street in view
    # objects:
    #   track:
    #     - person
    #     - cat
    #     - dog
    #   filters:
    #     person:
    #       mask:
    #         - 561,720,531,610,492,577,435,560,367,567,310,622,245,720
    # zones:
    #   front_yard:
    #     coordinates: 1280,720,1280,300,1280,90,1207,83,1194,220,997,209,755,194,633,200,374,216,0,242,0,720
    #     objects:
    #       - person
    #       - cat
    #       - dog
    #   front_yard_street:
    #     coordinates: 577,149,974,158,1139,171,1140,122,1154,61,976,0,739,0,238,0,190,37,80,94,90,197,226,174
    #     objects:
    #       - person
    # motion:
    #   mask:
    #     - 1280,720,1280,304,1254,298,1215,296,1185,291,1160,304,1139,332,1124,376,1094,414,1061,455,1059,531,1057,622,1125,720
    #     - 561,720,531,610,492,577,435,560,367,567,310,622,245,720
    #     - 178,45,262,0,405,31,353,92,322,105,382,124,390,154,360,177,274,209,185,211,126,130
    #     - 0,84,43,71,79,84,88,128,129,160,117,197,0,253
    #     - 580,103,611,105,641,155,639,175,557,185,534,130
    #     - 753,114,787,137,779,162,727,168,727,126
    #     - 1133,0,1280,0,1280,87,1280,168,1280,223,1280,254,1208,241,1155,217,1109,211,1097,178,1090,102
    #     - 1034,720,999,679,965,720
    live:
      stream_name: "front_door"
  garage:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/garage" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/garage_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      stationary:
        interval: 0
        threshold: 25
        max_frames:
          objects:
            # Disable stationary object tracking for cars in garage
            car: 0
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
        objects:
          - person
          - cat
          - dog
          - car
        retain:
          default: 20
          mode: motion
          objects:
            person: 30
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - "driveway"
        - "driveway_entrance"
        - "backyard"
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
    objects:
      track:
        - person
        - cat
        - dog
        - car
      filters:
        car:
          mask:
            - 1280,720,1280,610,1280,470,1201,442,1126,428,1050,444,1042,533,1019,591,992,678,1023,720
            - 336,307,467,124,573,63,571,0,395,0,0,0,0,428,0,720
        person:
          mask:
            - 1280,720,1280,610,1280,470,1201,442,1126,428,1050,444,1042,533,1019,591,992,678,1023,720
            - 807,720,808,679,645,667,590,605,558,720
    zones:
      driveway_entrance:
        coordinates: 681,83,765,152,849,87,1001,75,995,0,847,0,815,22,651,23,575,75,622,72
        objects:
          - car
          - cat
          - dog
        filters:
          car:
            min_score: 0.4
            max_area: 30000
            threshold: 0.6
      driveway:
        coordinates: 351,181,505,82,587,73,573,0,647,139,848,141,859,0,961,22,1079,50,1280,140,1280,720,0,720,0,408
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.4
            min_area: 2500
            min_ratio: 0.375
            threshold: 0.6
          cat:
            min_score: 0.4
            threshold: 0.6
          dog:
            min_score: 0.4
            threshold: 0.6
      backyard:
        coordinates: 0,195,0,151,113,98,359,29,576,0,579,50,390,147,412,228,63,549,0,408
        objects:
          - person
          - cat
          - dog
        filters:
          # Add filters due to small coverage area to increase detection
          person:
            min_area: 600
            min_score: 0.4
            threshold: 0.6
          cat:
            min_score: 0.4
            threshold: 0.6
          dog:
            min_score: 0.4
            threshold: 0.6
    motion:
      improve_contrast: True
      mask:
        - 495,0,0,0,0,77,0,154
        - 849,0,841,31,645,29,656,0
        - 1280,0,1280,88,1132,23,1107,41,1054,22,883,27,811,23,792,0
        - 917,720,1280,720,1280,677,924,666
        - 679,0,655,39,630,72,576,106,568,63,571,0
    live:
      stream_name: "garage"

frigate_detectors:
  # Recommended to have the same number of CPU detectors as available cameras
  cpu1:
    type: "cpu"
    num_threads: 4
  cpu2:
    type: "cpu"
    num_threads: 4

frigate_detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

frigate_ui:
  live_mode: "mse"
  use_experimental: False
  time_format: "24hour"
  date_style: "short"
  time_style: "medium"

### Logger
frigate_logger:
  default: "info"
