---
# Frigate configuration
frigate_mqtt_enabled: True
# Frigate MQTT Host is name of MQTT container running on the same host
# Only defined like this since communication through traefik doesn't
# work over SSL
frigate_mqtt_host: "mqtt_mosquitto"
frigate_mqtt_port: "{{ mqtt_mosquitto_port_tcp }}"
frigate_mqtt_user: "{{ mqtt_mosquitto_auth_credentials[0].username }}"
frigate_mqtt_password: "{{ mqtt_mosquitto_auth_credentials[0].password }}"

frigate_go2rtc:
  streams:
    front_door:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/front-door"
      - "ffmpeg:front_door#audio=opus"
    front_door_substream:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/front-door-sub"
      - "ffmpeg:front_door_substream#audio=opus"
    garage:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/rear-driveway"
      - "ffmpeg:front_door#audio=opus"
    garage_substream:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/rear-driveway-sub"
      - "ffmpeg:front_door_substream#audio=opus"
  # Necessary for establishing webrtc connection via live view
  webrtc:
    candidates:
      - frigate-001.hq1.chuanguyen.ca:8555
      - stun:8555

frigate_cameras:
  front_door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_door_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        required_zones:
          - front_yard
          - front_yard_street
        retain:
          default: 10
          mode: motion
          objects:
            person: 15
    snapshots:
      enabled: True
      bounding_box: True
    objects:
      track:
        - person
        - cat
        - dog
    zones:
      front_yard:
        coordinates: 0,360,592,360,640,306,640,129,583,94,317,76,0,97
      front_yard_street:
        coordinates: 349,65,640,95,640,41,333,0,31,41,44,98
        objects:
          - person
    motion:
      mask:
        - 640,360,583,360,550,301,540,229,591,179,640,153
    live:
      stream_name: "front_door"
  garage:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/garage" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/garage_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      stationary:
        interval: 0
        threshold: 25
        max_frames:
          objects:
            # Disable stationary object tracking for cars in garage
            car: 0
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
        objects:
          - person
          - cat
          - dog
          - car
        retain:
          default: 10
          mode: motion
          objects:
            person: 15
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - "driveway"
        - "driveway_entrance"
        - "backyard"
    objects:
      track:
        - person
        - cat
        - dog
        - car
    zones:
      driveway_entrance:
        coordinates: 436,61,407,105,368,103,341,61,329,40,284,37,300,0,423,0,493,0,495,38
        objects:
          - car
          - cat
          - dog
        filters:
          car:
            min_score: 0.4
            threshold: 0.6
      driveway:
        coordinates: 640,360,640,278,640,210,640,78,554,0,425,0,423,47,326,50,311,31,246,44,0,209,0,360
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.4
            threshold: 0.6
          cat:
            min_score: 0.4
            threshold: 0.6
          dog:
            min_score: 0.4
            threshold: 0.6
      backyard:
        coordinates: 0,195,0,78,75,26,192,26,219,111,31,285
        objects:
          - person
          - cat
          - dog
        filters:
          # Add filters due to small coverage area to increase detection
          person:
            min_score: 0.4
            threshold: 0.6
          cat:
            min_score: 0.4
            threshold: 0.6
          dog:
            min_score: 0.4
            threshold: 0.6
    live:
      stream_name: "garage"

frigate_detectors:
  cpu1:
    type: "cpu"
    num_threads: 6

frigate_detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

frigate_ui:
  live_mode: "mse"
  use_experimental: False
  time_format: "24hour"
  date_style: "short"
  time_style: "medium"

### Logger
frigate_logger:
  default: "info"
