---
authelia_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.authelia1.rule=Host(`login.{{ home_lan_domain }}`)"
  - "traefik.http.routers.authelia1.entrypoints=websecure"
  - "traefik.http.routers.authelia1.middlewares=authelia_secureHeaders@file"
  - "traefik.http.routers.authelia1.service=authelia-svc"
  - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
  - "traefik.http.routers.authelia1.tls=true"
  - "traefik.http.routers.authelia1.tls.certresolver=letsEncrypt"

authelia_config_listen_port: 9091
authelia_config_log_level: "info"

authelia_config_log_default_redirection: "https://login.{{ home_lan_domain }}"
authelia_config_totp_issuer: "{{ home_lan_domain }}"

# Indicates secret provided via a file
authelia_config_jwt_secret_external: true
authelia_config_jwt_secret: "{{ vault_authelia_config_jwt_secret }}"

authelia_config_authentication_backend_file: true

authelia_config_access_control_default_policy: "deny"

authelia_config_access_control_networks:
  - name: "home_internal"
    networks:
      - "{{ home_lan_cidr }}"
      - "{{ home_vpn_cidr }}"

authelia_config_access_control_rules:
  # Ensures any communication directly from HA to Frigate is bypassed
  - domains:
      - "frigate-001.{{ home_lan_domain }}"
      - "zwave.{{ home_lan_domain }}"
    resources: []
    policy: "bypass"
    networks:
      - "{{ lookup('community.general.dig', 'home-assistant-001.'+home_lan_domain) }}"
  # Access to Home Assistant's API to Frigate shouldn't authenticate
  # for ease of viewing (Discord, app notifications)
  - domains:
      - "home-assistant-001.{{ home_lan_domain }}"
    resources: []
    policy: "bypass"
    networks: []
  # Access to Frigate media isn't authenticated for ease of viewing (Discord, app notifications)
  # URLs with the resource path starting as what's defined will be bypassed
  - domains:
      - "frigate-001.{{ home_lan_domain }}"
    resources:
      - "^/live/webrtc/"
    policy: "bypass"
    networks: []
  - domains:
      - "*.{{ home_lan_domain }}"
    resources: []
    policy: "two_factor"
    networks:
      - "home_internal"

authelia_config_password_policy_standard_enabled: "false"
authelia_config_password_policy_zxcvbn_enabled: "true"
authelia_config_password_policy_zxcvbn_min_score: 3

# Indicates secret provided via a file
authelia_config_session_secret_external: true
authelia_config_session_secret: "{{ vault_authelia_config_session_secret }}"
authelia_config_session_domain: "{{ home_lan_domain }}"

authelia_notifier_disable_startup_check: "false"
authelia_notifier_filesystem: false

authelia_notifier_smtp: true
authelia_notifier_smtp_username: "{{ home_smtp_relay_server_username }}"
authelia_notifier_smtp_password_external: true
authelia_notifier_smtp_password: "{{ vault_authelia_notifier_smtp_password }}"
authelia_notifier_smtp_host: "{{ home_smtp_relay_server }}"
authelia_notifier_smtp_port: 465
authelia_notifier_smtp_sender: "authelia@{{ home_lan_domain_public }}"
authelia_notifier_smtp_subject: "[Authelia] {title}"

authelia_storage_encryption_key: "{{ vault_authelia_storage_encryption_key }}"

authelia_local_users: "{{ vault_authelia_local_users }}"

authelia_config_ntp_enabled: false
authelia_config_ntp_address: "0.pool.ntp.org:123"
authelia_config_ntp_version: 3
authelia_config_ntp_max_desync: 3s
authelia_config_ntp_disable_startup_check: "false"
authelia_config_ntp_disable_failure: "false"

### OAuth
authelia_config_identity_providers_enabled: true
authelia_config_oidc_enabled: true

authelia_config_oidc_settings:
  issuer_private_key: "{{ vault_authelia_config_issuer_private_key }}"

authelia_config_oidc_clients: "{{ vault_authelia_config_oidc_clients }}"
