# MQTT Mosquitto
mqtt_mosquitto_port_tcp: 1883
mqtt_mosquitto_port_secure_tcp: 8883
mqtt_mosquitto_port_web_socket: 9001

# Frigate
frigate_port_web: 5000
frigate_port_rtsp: 8554
frigate_port_webrtc: 8555

frigate_container_data_dir_sub_folders:
  - "frigate-config"

frigate_container_volumes:
  binds:
    - source: "./frigate-config"
      target: "/config/"
    - source: "/media/media-frigate"
      target: "/media/frigate"
    - source: "/etc/localtime"
      target: "/etc/localtime:ro"
