---
# Container config
frigate_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  ### Frigate rules
  - "traefik.http.routers.frigate1.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`) && (PathPrefix(`/`) && !PathPrefix(`/live/webrtc`))"
  - "traefik.http.routers.frigate1.entrypoints=websecure"
  - "traefik.http.routers.frigate1.middlewares=secureHeaders@file,authelia"
  - "traefik.http.routers.frigate1.service=frigate-svc"
  - "traefik.http.services.frigate-svc.loadbalancer.server.port={{ frigate_port_web }}"
  - "traefik.http.routers.frigate1.tls=true"
  - "traefik.http.routers.frigate1.tls.certresolver=letsEncrypt"
  ### Go2RTC rules https://github.com/blakeblackshear/frigate/pull/8762#issuecomment-1875109664
  - "traefik.http.routers.frigate-go2rtc.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`) && PathPrefix(`/live/webrtc`)"
  - "traefik.http.routers.frigate-go2rtc.entrypoints=websecure"
  - "traefik.http.routers.frigate-go2rtc.middlewares=secureHeaders@file,frigate_go2rtc_strip_webrtc_prefix@file,authelia"
  - "traefik.http.routers.frigate-go2rtc.service=frigate-go2rtc-svc"
  - "traefik.http.services.frigate-go2rtc-svc.loadbalancer.server.port={{ frigate_port_go2rtc }}"
  - "traefik.http.routers.frigate-go2rtc.tls=true"
  - "traefik.http.routers.frigate-go2rtc.tls.certresolver=letsEncrypt"

frigate_use_custom_go2rtc: false
frigate_custom_go2rtc_version: ""

# Frigate configuration
frigate_mqtt_enabled: True
# Frigate MQTT Host is name of MQTT container running on the same host
# Only defined like this since communication through traefik doesn't
# work over SSL
frigate_mqtt_host: "mqtt_mosquitto"
frigate_mqtt_port: "{{ mqtt_mosquitto_port_tcp }}"
frigate_mqtt_user: "{{ mqtt_mosquitto_auth_credentials[0].username }}"
frigate_mqtt_password: "{{ mqtt_mosquitto_auth_credentials[0].password }}"

frigate_auth:
  # Optional: Enable authentication
  enabled: False

frigate_go2rtc:
  streams:
    front_door:
      - "rtsp://{{ docker_wyze_bridge_stream_username }}:{{ docker_wyze_bridge_stream_api_key }}@home-assistant-001.{{ home_lan_domain }}:8554/front-door"
      - "ffmpeg:front_door#audio=opus"
    front_door_bell:
      - "ffmpeg:http://doorbell-front.{{ home_lan_domain }}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={{ reolink_cameras_username }}&password={{ reolink_cameras_password }}#video=copy#audio=copy#audio=opus"
      # - "ffmpeg:front_door_bell#audio=opus"
    front_door_bell_substream:
      - "ffmpeg:http://doorbell-front.{{ home_lan_domain }}/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={{ reolink_cameras_username }}&password={{ reolink_cameras_password }}"
    garage:
      - "rtsp://{{ docker_wyze_bridge_stream_username }}:{{ docker_wyze_bridge_stream_api_key }}@home-assistant-001.{{ home_lan_domain }}:8554/rear-driveway"
      - "ffmpeg:garage#audio=opus"
  # Necessary for establishing webrtc connection via live view
  webrtc:
    candidates:
      - frigate-001.{{ home_lan_domain }}:8555
      - stun:8555

frigate_cameras:
  front_door_bell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door_bell?video=copy&audio=aac" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_door_bell_substream?video=copy" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10
    review:
      alerts:
        labels:
          - person
        required_zones:
          - front_yard_left
          - front_yard_right
          - front_yard_walkway
      detections:
        labels:
          - cat
          - dog
          - bird
          - mouse
        required_zones:
          - front_yard_left
          - front_yard_right
          - front_yard_walkway
    record:
      enabled: True
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 20
          mode: motion
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 10
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
      required_zones:
        - front_yard_left
        - front_yard_right
        - front_yard_walkway
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - mouse
      filters:
        person:
          mask:
            - 0,0,470,0,496,66,518,205,501,205,450,205,435,196,398,181,364,212,77,207,69,192,53,176,23,177,0,203
    zones:
      front_yard_left:
        coordinates: 162,258,40,255,80,187,27,167,0,200,0,253,0,480,121,480,246,480
      front_yard_right:
        coordinates: 217,255,378,247,382,198,411,189,513,200,510,253,503,303,487,373,427,389,354,392,301,341,232,279
      front_yard_walkway:
        coordinates: 640,480,640,108,501,118,501,325,427,371,348,382,222,266,168,267,222,407,0,412,0,480
        inertia: 10
        filters:
          person:
            min_area: 800
    motion:
      mask:
        - 0,0,470,0,496,66,518,205,501,205,450,205,435,196,398,181,364,212,77,207,69,192,53,176,23,177,0,203
        - 368,451,640,447,640,480,371,480
    live:
      stream_name: "front_door_bell"
  front_door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    review:
      alerts:
        labels:
          - person
        required_zones:
          - front_yard
      detections:
        labels:
          - person
          - cat
          - dog
          - bird
          - mouse
        required_zones:
          - front_yard
          - front_yard_street
    record:
      enabled: True
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 20
          mode: motion
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 10
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - mouse
      filters:
        person:
          mask:
            - 633,266,631,224,588,209,542,215,556,264
            - 608,0,1280,0,1280,156,1136,129,825,87,286,97,90,201,0,163,0,0
            - 796,132,793,54,780,35,755,38,744,70,763,132
    zones:
      front_yard:
        coordinates: 1280,720,1280,300,1280,143,1175,130,1181,185,1176,298,832,277,532,267,146,293,0,296,0,720
        objects:
          - person
          - cat
          - dog
          - bird
          - mouse
      front_yard_street:
        coordinates: 678,280,949,287,1176,292,1176,172,1280,153,1280,0,976,0,739,0,0,0,0,302,243,293
        objects:
          - person
    motion:
      mask:
        - 1280,720,1280,384,1237,370,1163,394,1120,457,1124,543,1125,665,1156,720
        - 608,0,1280,0,1280,140,1229,90,1131,111,825,87,260,79,90,201,0,163,0,0
    live:
      stream_name: "front_door"
  garage:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/garage" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    review:
      alerts:
        labels:
          - person
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
      detections:
        labels:
          - car
          - cat
          - dog
          - bird
          - mouse
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
    record:
      enabled: True
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 20
          mode: motion
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 10
          mode: motion
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - "driveway"
        - "driveway_entrance"
        - "backyard"
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - bird
        - mouse
      filters:
        car:
          mask:
            - 219,321,416,146,474,72,474,0,395,0,0,0,0,428,0,531
            - 0,545,112,410,248,209,1112,212,1280,320,1280,438,1280,720,0,720
        person:
          mask:
            - 1280,720,1147,456,1064,443,966,459,926,699,443,670,423,720,1023,720
    zones:
      driveway_entrance:
        coordinates: 408,184,888,191,892,0,515,0
        inertia: 1
        loitering_time: 0
        objects:
          - person
          - car
          - cat
          - dog
          - bird
          - mouse
        filters:
          car:
            min_score: 0.2
            threshold: 0.30
      driveway:
        coordinates: 243,276,512,89,556,247,819,243,954,112,1045,56,1280,165,1280,720,0,720,0,553
        objects:
          - person
          - car
          - cat
          - dog
          - bird
          - mouse
      backyard:
        coordinates: 0,195,0,0,456,0,462,76,451,114,0,536,0,408
        objects:
          - person
          - cat
          - dog
          - bird
          - mouse
    motion:
      enabled: True
      mask:
        - 112,81,395,21,536,26,543,0,0,0,0,92
        - 884,0,1280,0,1280,138,1165,69,1158,107,1017,48,893,41,735,46,533,48,530,0
        - 917,720,1280,720,1280,677,924,666
    live:
      stream_name: "garage"

frigate_detectors:
  ov:
    type: "openvino"
    device: "CPU"
  # # Recommended to have the same number of CPU detectors as available cameras
  # cpu1:
  #   type: "cpu"
  #   num_threads: 4
  # cpu2:
  #   type: "cpu"
  #   num_threads: 4

frigate_detectors_model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

frigate_detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking

frigate_ui:
  time_format: "24hour"
  date_style: "short"
  time_style: "medium"

### Logger
frigate_logger:
  default: "debug"
