---
# Container config
frigate_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  ### Frigate rules
  - "traefik.http.routers.frigate1.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`) && (PathPrefix(`/`) && !PathPrefix(`/live/webrtc`))"
  - "traefik.http.routers.frigate1.entrypoints=websecure"
  - "traefik.http.routers.frigate1.middlewares=secureHeaders@file,authelia"
  - "traefik.http.routers.frigate1.service=frigate-svc"
  - "traefik.http.services.frigate-svc.loadbalancer.server.port={{ frigate_port_web }}"
  - "traefik.http.routers.frigate1.tls=true"
  - "traefik.http.routers.frigate1.tls.certresolver=letsEncrypt"
  ### Go2RTC rules https://github.com/blakeblackshear/frigate/pull/8762#issuecomment-1875109664
  - "traefik.http.routers.frigate-go2rtc.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`) && PathPrefix(`/live/webrtc`)"
  - "traefik.http.routers.frigate-go2rtc.entrypoints=websecure"
  - "traefik.http.routers.frigate-go2rtc.middlewares=secureHeaders@file,frigate_go2rtc_strip_webrtc_prefix@file,authelia"
  - "traefik.http.routers.frigate-go2rtc.service=frigate-go2rtc-svc"
  - "traefik.http.services.frigate-go2rtc-svc.loadbalancer.server.port={{ frigate_port_go2rtc }}"
  - "traefik.http.routers.frigate-go2rtc.tls=true"
  - "traefik.http.routers.frigate-go2rtc.tls.certresolver=letsEncrypt"

frigate_use_custom_go2rtc: false
frigate_custom_go2rtc_version: ""

# Frigate configuration
frigate_mqtt_enabled: true
# Frigate MQTT Host is name of MQTT container running on the same host
# Only defined like this since communication through traefik doesn't
# work over SSL
frigate_mqtt_host: "mqtt_mosquitto"
frigate_mqtt_port: "{{ mqtt_mosquitto_port_tcp }}"
frigate_mqtt_user: "{{ mqtt_mosquitto_auth_credentials[0].username }}"
frigate_mqtt_password: "{{ mqtt_mosquitto_auth_credentials[0].password }}"

frigate_auth:
  # Optional: Enable authentication
  enabled: false

frigate_go2rtc:
  streams:
    front_door:
      - "rtsp://{{ docker_wyze_bridge_stream_username }}:{{ docker_wyze_bridge_stream_api_key }}@home-assistant-001.{{ home_lan_domain }}:8554/front-door"
      - "ffmpeg:front_door#audio=opus"
    front_door_bell:
      - "ffmpeg:http://doorbell-front.{{ home_lan_domain }}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={{ reolink_cameras_username }}&password={{ reolink_cameras_password }}#video=copy#audio=copy#audio=opus"
      # - "ffmpeg:front_door_bell#audio=opus"
    front_door_bell_substream:
      - "ffmpeg:http://doorbell-front.{{ home_lan_domain }}/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={{ reolink_cameras_username }}&password={{ reolink_cameras_password }}"
    garage:
      - "rtsp://{{ docker_wyze_bridge_stream_username }}:{{ docker_wyze_bridge_stream_api_key }}@home-assistant-001.{{ home_lan_domain }}:8554/rear-driveway"
      - "ffmpeg:garage#audio=opus"
  # Necessary for establishing webrtc connection via live view
  webrtc:
    candidates:
      - frigate-001.{{ home_lan_domain }}:8555
      - stun:8555

frigate_cameras:
  front_door_bell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door_bell" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_door_bell_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 10
    review:
      alerts:
        labels:
          - person
        required_zones:
          - front_yard_left
          - front_yard_right
          - front_yard_walkway
      detections:
        labels:
          - cat
          - dog
          - bird
          - mouse
        required_zones:
          - front_yard_left
          - front_yard_right
          - front_yard_walkway
    record:
      enabled: true
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 20
          mode: motion
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 10
          mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
      required_zones:
        - front_yard_left
        - front_yard_right
        - front_yard_walkway
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - mouse
      filters:
        person:
          mask:
            - 0,0,0.734,0,0.775,0.138,0.809,0.427,0.783,0.427,0.703,0.427,0.68,0.408,0.622,0.377,0.569,0.442,0.12,0.431,0.108,0.4,0.083,0.367,0.036,0.369,0,0.423
    zones:
      front_yard_left:
        coordinates: 0.253,0.537,0.062,0.531,0.125,0.39,0.042,0.348,0,0.417,0,0.527,0,1,0.189,1,0.384,1
      front_yard_right:
        coordinates: 0.339,0.531,0.591,0.515,0.597,0.412,0.642,0.394,0.802,0.417,0.797,0.527,0.786,0.631,0.761,0.777,0.667,0.81,0.553,0.817,0.47,0.71,0.362,0.581
      front_yard_walkway:
        coordinates: 1,1,1,0.225,0.783,0.246,0.783,0.677,0.667,0.773,0.544,0.796,0.347,0.554,0.263,0.556,0.347,0.848,0,0.858,0,1
        inertia: 10
        filters:
          person:
            min_area: 800
    motion:
      mask:
        - 0,0,0.734,0,0.775,0.138,0.809,0.427,0.783,0.427,0.703,0.427,0.68,0.408,0.622,0.377,0.569,0.442,0.12,0.431,0.108,0.4,0.083,0.367,0.036,0.369,0,0.423
        - 0.575,0.94,1,0.931,1,1,0.58,1
    live:
      stream_name: "front_door_bell"
  front_door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    review:
      alerts:
        labels:
          - person
        required_zones:
          - front_yard
      detections:
        labels:
          - person
          - cat
          - dog
          - bird
          - mouse
        required_zones:
          - front_yard
          - front_yard_street
    record:
      enabled: true
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 20
          mode: motion
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 10
          mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
    objects:
      track:
        - person
        - cat
        - dog
        - bird
        - mouse
      filters:
        person:
          mask:
            - 0.495,0.369,0.493,0.311,0.459,0.29,0.423,0.299,0.434,0.367
            - 0.475,0,1,0,1,0.217,0.887,0.179,0.645,0.121,0.223,0.135,0.07,0.279,0,0.226,0,0
            - 0.622,0.183,0.62,0.075,0.609,0.049,0.59,0.053,0.581,0.097,0.596,0.183
    zones:
      front_yard:
        coordinates: 1,1,1,0.417,1,0.199,0.918,0.181,0.923,0.257,0.919,0.414,0.65,0.385,0.416,0.371,0.114,0.407,0,0.411,0,1
        objects:
          - person
          - cat
          - dog
          - bird
          - mouse
      front_yard_street:
        coordinates: 0.53,0.389,0.741,0.399,0.919,0.406,0.919,0.239,1,0.212,1,0,0.762,0,0.577,0,0,0,0,0.419,0.19,0.407
        objects:
          - person
    motion:
      mask:
        - 1,1,1,0.533,0.966,0.514,0.909,0.547,0.875,0.635,0.878,0.754,0.879,0.924,0.903,1
        - 0.475,0,1,0,1,0.194,0.96,0.125,0.884,0.154,0.645,0.121,0.203,0.11,0.07,0.279,0,0.226,0,0
    live:
      stream_name: "front_door"
  garage:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/garage" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    review:
      alerts:
        labels:
          - person
          - car
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
      detections:
        labels:
          - cat
          - dog
          - bird
          - mouse
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
    record:
      enabled: true
      alerts:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 20
          mode: motion
      detections:
        pre_capture: 10
        post_capture: 10
        retain:
          days: 10
          mode: motion
    snapshots:
      enabled: true
      bounding_box: true
      required_zones:
        - "driveway"
        - "driveway_entrance"
        - "backyard"
      retain:
        # Required: Default retention days (default: shown below)
        default: 20
        # Optional: Per object retention days
        objects:
          person: 30
    objects:
      track:
        - person
        - cat
        - dog
        - car
        - bird
        - mouse
      filters:
        car:
          mask:
            - 0.423,0.007,0.42,0.068,0.699,0.072,0.699,0.002
            - 0,0.757,0.087,0.569,0.194,0.29,0.869,0.294,1,0.444,1,0.608,1,1,0,1
            - 0.171,0.446,0.325,0.203,0.37,0.1,0.37,0,0.309,0,0,0,0,0.594,0,0.738
        person:
          mask:
            - 1,1,0.896,0.633,0.831,0.615,0.755,0.637,0.723,0.971,0.346,0.931,0.33,1,0.799,1
    zones:
      driveway_entrance:
        coordinates: 0.319,0.256,0.694,0.265,0.697,0,0.402,0
        inertia: 1
        loitering_time: 0
        objects:
          - person
          - car
          - cat
          - dog
          - bird
          - mouse
        filters:
          car:
            min_score: 0.2
            threshold: 0.30
      driveway:
        coordinates: 0.19,0.383,0.4,0.124,0.434,0.343,0.64,0.338,0.745,0.156,0.816,0.078,1,0.229,1,1,0,1,0,0.768
        objects:
          - person
          - car
          - cat
          - dog
          - bird
          - mouse
      backyard:
        coordinates: 0,0.271,0,0,0.356,0,0.361,0.106,0.352,0.158,0,0.744,0,0.567
        objects:
          - person
          - cat
          - dog
          - bird
          - mouse
    motion:
      enabled: true
      mask:
        - 0.087,0.113,0.309,0.029,0.419,0.036,0.424,0,0,0,0,0.128
        - 0.691,0,1,0,1,0.192,0.91,0.096,0.905,0.149,0.795,0.067,0.698,0.057,0.574,0.064,0.416,0.067,0.414,0
        - 0.716,1,1,1,1,0.94,0.722,0.925
    live:
      stream_name: "garage"

frigate_detectors:
  ov:
    type: "openvino"
    device: "CPU"
  # # Recommended to have the same number of CPU detectors as available cameras
  # cpu1:
  #   type: "cpu"
  #   num_threads: 4
  # cpu2:
  #   type: "cpu"
  #   num_threads: 4

frigate_detectors_model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

frigate_detect:
  width: 1280
  height: 720
  fps: 5
  enabled: true
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking

frigate_ui:
  time_format: "24hour"
  date_style: "short"
  time_style: "medium"

### Logger
frigate_logger:
  default: "debug"
