# MQTT Mosquitto
mqtt_mosquitto_port_tcp: 1883
mqtt_mosquitto_port_secure_tcp: 8883
mqtt_mosquitto_port_web_socket: 9001

# Frigate
frigate_port_web: 5000
frigate_port_rtsp: 8554
frigate_port_webrtc: 8555

# Frigate configuration
frigate_mqtt_enabled: True
frigate_mqtt_host: "mqtt-001.{{ home_lan_domain }}"
frigate_mqtt_port: "{{ mqtt_mosquitto_port_secure_tcp }}"
frigate_mqtt_user: "{{ mqtt_mosquitto_auth_credentials[0].username }}"
frigate_mqtt_password: "{{ mqtt_mosquitto_auth_credentials[0].password }}"
