---
# Container config
frigate_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.frigate1.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`)"
  - "traefik.http.routers.frigate1.entrypoints=websecure"
  - "traefik.http.routers.frigate1.middlewares=secureHeaders@file,authelia"
  - "traefik.http.routers.frigate1.service=frigate-svc"
  - "traefik.http.services.frigate-svc.loadbalancer.server.port={{ frigate_port_web }}"
  - "traefik.http.routers.frigate1.tls=true"
  - "traefik.http.routers.frigate1.tls.certresolver=letsEncrypt"

# Frigate configuration
frigate_mqtt_enabled: True
# Frigate MQTT Host is name of MQTT container running on the same host
# Only defined like this since communication through traefik doesn't
# work over SSL
frigate_mqtt_host: "mqtt_mosquitto"
frigate_mqtt_port: "{{ mqtt_mosquitto_port_tcp }}"
frigate_mqtt_user: "{{ mqtt_mosquitto_auth_credentials[0].username }}"
frigate_mqtt_password: "{{ mqtt_mosquitto_auth_credentials[0].password }}"

frigate_go2rtc:
  streams:
    front_door:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/front-door"
      - "ffmpeg:front_door#audio=opus"
    front_door_substream:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/front-door-sub"
      - "ffmpeg:front_door_substream#audio=opus"
    garage:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/rear-driveway"
      - "ffmpeg:front_door#audio=opus"
    garage_substream:
      - "rtsp://home-assistant-001.hq1.chuanguyen.ca:8556/rear-driveway-sub"
      - "ffmpeg:front_door_substream#audio=opus"
  # Necessary for establishing webrtc connection via live view
  webrtc:
    candidates:
      - frigate-001.hq1.chuanguyen.ca:8555
      - stun:8555

frigate_cameras:
  front_door: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/front_door" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/front_door_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        objects:
          - person
          - cat
          - dog
        required_zones:
          - front_yard
          - front_yard_street
        retain:
          default: 10
          mode: motion
          objects:
            person: 15
    snapshots:
      enabled: True
      bounding_box: True
    objects:
      track:
        - person
        - cat
        - dog
    zones:
      front_yard:
        coordinates: 1280,720,1280,300,1280,90,1207,83,1201,188,1003,194,860,192,750,178,629,182,511,185,357,190,140,216,63,193,0,179,0,720
        objects:
          - person
          - cat
          - dog
      front_yard_street:
        coordinates: 577,149,974,158,1139,171,1140,122,1154,61,976,0,739,0,238,0,190,37,80,94,90,197,226,174
        objects:
          - person
    motion:
      mask:
        - 1280,720,1280,304,1254,298,1215,296,1185,291,1160,304,1139,332,1124,376,1094,414,1061,455,1059,531,1057,622,1125,720
        - 561,720,531,610,492,577,435,560,379,599,310,622,314,720
        - 178,45,262,0,405,31,353,92,322,105,382,124,390,154,360,177,274,209,185,211,126,130
        - 0,84,43,71,79,84,88,128,129,160,117,197,0,253
        - 580,103,611,105,641,155,639,175,557,185,534,130
        - 753,114,787,137,779,162,727,168,727,126
        - 1133,0,1280,0,1280,87,1280,168,1280,223,1280,254,1208,241,1155,217,1109,211,1097,178,1090,102
    ### Zone and masks for 360p
    # zones:
    #   front_yard:
    #     coordinates: 0,360,592,360,640,306,640,129,583,94,317,76,0,97
    #   front_yard_street:
    #     coordinates: 349,65,640,95,640,41,333,0,31,41,44,98
    #     objects:
    #       - person
    # motion:
    #   mask:
    #     - 640,360,583,360,550,301,540,229,591,179,640,153
    live:
      stream_name: "front_door"
  garage:
    ffmpeg:
      inputs:
        - path: "rtsp://127.0.0.1:8554/garage" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - record
        - path: "rtsp://127.0.0.1:8554/garage_substream" # Restream connection
          input_args: "preset-rtsp-restream"
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 10
      stationary:
        interval: 0
        threshold: 25
        max_frames:
          objects:
            # Disable stationary object tracking for cars in garage
            car: 0
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
          - "driveway"
          - "driveway_entrance"
          - "backyard"
        objects:
          - person
          - cat
          - dog
          - car
        retain:
          default: 10
          mode: motion
          objects:
            person: 15
    snapshots:
      enabled: True
      bounding_box: True
      required_zones:
        - "driveway"
        - "driveway_entrance"
        - "backyard"
    objects:
      track:
        - person
        - cat
        - dog
        - car
    zones:
      driveway_entrance:
        coordinates: 681,83,765,152,849,87,1001,75,995,0,847,0,848,37,650,39,575,75,622,72
        objects:
          - car
          - cat
          - dog
        filters:
          car:
            min_score: 0.4
            threshold: 0.6
      driveway:
        coordinates: 351,181,505,82,587,73,573,0,647,139,848,141,859,0,961,22,1079,50,1280,140,1280,720,0,720,0,408
        objects:
          - person
          - cat
          - dog
        filters:
          person:
            min_score: 0.5
            threshold: 0.7
          cat:
            min_score: 0.4
            threshold: 0.6
          dog:
            min_score: 0.4
            threshold: 0.6
      backyard:
        coordinates: 0,195,0,151,113,98,359,29,560,0,573,73,423,139,448,235,63,549,0,408
        objects:
          - person
          - cat
          - dog
        filters:
          # Add filters due to small coverage area to increase detection
          person:
            min_score: 0.4
            threshold: 0.6
          cat:
            min_score: 0.4
            threshold: 0.6
          dog:
            min_score: 0.4
            threshold: 0.6
    motion:
      improve_contrast: True
      mask:
        - 495,0,0,0,0,77,0,154
        - 849,0,841,31,645,29,656,0
        - 1280,0,1280,88,1136,22,883,27,811,23,792,0
        - 917,720,1280,720,1280,677,924,666
    ### Zone and masks for 360p
    # zones:
    #   driveway_entrance:
    #     coordinates: 443,40,413,64,407,105,368,103,341,61,329,40,284,37,300,0,423,0,493,0,495,38
    #     objects:
    #       - car
    #       - cat
    #       - dog
    #     filters:
    #       car:
    #         min_score: 0.4
    #         threshold: 0.6
    #   driveway:
    #     coordinates: 640,360,640,278,640,210,640,78,554,0,425,0,423,47,326,50,311,31,246,44,0,209,0,360
    #     objects:
    #       - person
    #       - cat
    #       - dog
    #     filters:
    #       person:
    #         min_score: 0.4
    #         threshold: 0.6
    #       cat:
    #         min_score: 0.4
    #         threshold: 0.6
    #       dog:
    #         min_score: 0.4
    #         threshold: 0.6
    #   backyard:
    #     coordinates: 0,195,0,78,75,26,192,26,219,111,31,285
    #     objects:
    #       - person
    #       - cat
    #       - dog
    #     filters:
    #       # Add filters due to small coverage area to increase detection
    #       person:
    #         min_score: 0.4
    #         threshold: 0.6
    #       cat:
    #         min_score: 0.4
    #         threshold: 0.6
    #       dog:
    #         min_score: 0.4
    #         threshold: 0.6
    live:
      stream_name: "garage"

frigate_detectors:
  # Recommended to have the same number of CPU detectors as available cameras
  cpu1:
    type: "cpu"
    num_threads: 4
  cpu2:
    type: "cpu"
    num_threads: 4

frigate_detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50

frigate_ui:
  live_mode: "mse"
  use_experimental: False
  time_format: "24hour"
  date_style: "short"
  time_style: "medium"

### Logger
frigate_logger:
  default: "info"
