system_packages:
  - autoconf
  - autofs
  - build-essential
  - cron
  - fail2ban
  - libdata-validate-ip-perl
  - net-tools
  - p7zip-full
  - unzip

fail2ban_ignoreip:
  - "{{ home_lan_cidr }}"

ufw_rules:
  add:
    - comment: "Permits incoming SSH connections"
      rule: allow
      delete: no
      from_ip: any
      to_ip: any
      from_port: null
      to_port: "22"
      proto: tcp
    - comment: "Permits incoming TCP connections to iperf3"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "5201"
      proto: tcp
    - comment: "Permits incoming UDP connections to iperf3"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "5201"
      proto: udp
    - comment: "Permits incoming Prometheus node exporter connections"
      rule: allow
      delete: no
      from_ip: "any"
      to_ip: any
      from_port: null
      to_port: "9100"
      proto: any
  remove:
    -
