system_packages:
  - autoconf
  - autofs
  - build-essential
  - cron
  - fail2ban
  - libdata-validate-ip-perl
  - net-tools
  - p7zip-full
  - unzip

fail2ban_ignoreip:
  - "{{ home_lan_cidr }}"

ufw_rules:
  add:
    - comment: "Permits incoming SSH connections"
      rule: allow
      delete: no
      from_ip: any
      to_ip: any
      from_port: null
      to_port: "22"
      proto: tcp
    - comment: "Permits incoming HTTP connections"
      rule: allow
      delete: no
      from_ip: any
      to_ip: any
      from_port: null
      to_port: "80"
      proto: tcp
    - comment: "Permits incoming HTTPS connections"
      rule: allow
      delete: no
      from_ip: any
      to_ip: any
      from_port: null
      to_port: "443"
      proto: tcp
    - comment: "Permits incoming TCP connections to iperf3"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "5201"
      proto: tcp
    - comment: "Permits incoming UDP connections to iperf3"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "5201"
      proto: udp
    - comment: "Permits incoming Prometheus node exporter connections"
      rule: allow
      delete: no
      from_ip: "any"
      to_ip: any
      from_port: null
      to_port: "9100"
      proto: any
    - comment: "Permits incoming connection to frigate web portal"
      rule: allow
      delete: no
      from_ip: "{{ lookup('community.general.dig', 'home-assistant-001.'+home_lan_domain) }}"
      to_ip: any
      from_port: null
      to_port: "{{ frigate_port_web }}"
      proto: tcp
    - comment: "Permits incoming connection to frigate RTSP feeds"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "{{ frigate_port_rtsp }}"
      proto: any
    - comment: "Permits incoming connection to frigate WebRTC (TCP/UDP)"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "{{ frigate_port_webrtc }}"
      proto: any
    - comment: "Permits incoming connection to MQTT (Secure) Mosquitto TCP"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "{{ mqtt_mosquitto_port_secure_tcp }}"
      proto: tcp
    - comment: "Permits incoming connection to MQTT Mosquitto Websocket"
      rule: allow
      delete: no
      from_ip: "{{ home_lan_cidr }}"
      to_ip: any
      from_port: null
      to_port: "{{ mqtt_mosquitto_port_web_socket }}"
      proto: any
  remove:
    -
