---
- name: "PLAY: Prep nodes for k3s"
  hosts: k3s_cluster
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/core-setup/configure-baseline"
      tags: [baseline]

    - role: "kubernetes/k3s/core-setup/install-k3s"
      tags: [baseline]

- name: "PLAY: Baseline master nodes"
  hosts: k3s_masters
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/core-setup/configure-masters"
      tags: [nodes-masters]

- name: "PLAY: Baseline worker nodes"
  hosts: k3s_workers
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/core-setup/configure-workers"
      tags: [nodes-workers]
