---
- name: "PLAY: Prep nodes for k3s"
  hosts: k3s_cluster
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/core-setup/configure-baseline"
      tags: [baseline]

    - role: "kubernetes/k3s/core-setup/install-k3s"
      tags: [baseline]

- name: "PLAY: Baseline master nodes"
  hosts: k3s_masters
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/core-setup/configure-masters"
      tags: [nodes-masters]

- name: "PLAY: Baseline worker nodes"
  hosts: k3s_workers
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/core-setup/configure-workers"
      tags: [nodes-workers]

### Localhost configuration

- name: "PLAY: Copy Kube Config to local client"
  hosts: k3s_masters
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/clients/copy-kube-config"
      tags: [local-kube-client]

- name: "PLAY: Configure local clients to connect to k3s cluster"
  hosts: localhost

  roles:
    - role: "kubernetes/k3s/clients/configure-local-clients-for-k3s-connection"
      tags: [local-kube-client]
