---
# Execute prior to other Playbooks
# Onboards server for management

- name: "PLAY: Baselining servers"
  hosts: all
  gather_facts: true

  roles:
    - role: install-system-packages
      tags: [baseline]
    - role: configure-hostname
      tags: [baseline]
    - role: configure-local-users
      tags: [baseline]
    - role: configure-netplan
      tags: [baseline, network]
