---
- name: "PLAY: Baselining servers"
  hosts: rbp4-001,family-docker-001
  gather_facts: true

  roles:
    - role: install-system-packages
      tags: [baseline]
    - role: configure-hostname
      tags: [baseline]
    - role: configure-timezone
      tags: [baseline, timezone]
    - role: configure-systemd-resolved
      tags: [baseline, refresh, network]
    - role: configure-cloud-init
      tags: [baseline, refresh, network]
    - role: configure-netplan
      tags: [baseline, refresh]
    - role: configure-ssh-server
      tags: [baseline, refresh, security]
    - role: configure-ufw
      tags: [baseline, refresh, network, security]
    - role: configure-fail2ban
      tags: [baseline, refresh, security]
    - role: configure-cron
      tags: [baseline, refresh]
    - role: configure-autofs
      tags: [baseline, refresh]
    - role: configure-docker
      tags: [baseline, refresh, docker]
    - role: configure-prometheus-node-exporter
      tags: [baseline, monitoring, refresh]

- name: "PLAY: Baseline Proxmox"
  hosts: proxmox_servers
  gather_facts: true

  roles:
    - role: configure-sudoers
      tags: [baseline, refresh, security, sudoer]
    - role: configure-ssh-server
      tags: [baseline, refresh, security]
    - role: configure-prometheus-node-exporter
      tags: [baseline, monitoring, refresh]
    - role: configure-postfix
      tags: [baseline, postfix]
