---
- name: "PLAY: Deploy services"
  hosts: rbp4-001
  gather_facts: true

  roles:
    - role: "deploy-portainer"
      tags: [services, portainer]

    - role: "deploy-pihole"
      tags: [services, pihole]

    - role: "configure-ddclient"
      tags: [services, vpn, ddclient]

    - role: "deploy-wireguard"
      tags: [services, vpn, wireguard]

    - role: "deploy-traefik"
      tags: [services, proxy, traefik]

    - role: "deploy-smtp-relay"
      tags: [services, smtp_relay]

    - role: "deploy-grafana"
      tags: [services, monitoring, grafana]

    - role: "deploy-prometheus"
      tags: [services, monitoring, prometheus, prometheus_core]

    - role: "deploy-prometheus-alertManager"
      tags: [services, monitoring, prometheus, alertmanager]

    - role: "deploy-prometheus-snmp-exporter"
      tags: [services, monitoring, prometheus, prometheus-exporter]

    - role: "deploy-prometheus-home-internet-monitoring"
      tags:
        [
          services,
          monitoring,
          prometheus,
          prometheus-exporter,
          home-internet-monitoring,
        ]

- name: "PLAY: Deploy home automation services"
  hosts: family-docker-001
  gather_facts: true

  roles:
    - role: "deploy-traefik"
      tags: [services, proxy, traefik]
      vars:
        traefik_http_rule_hostname: "traefik-001"

    - role: "deploy-portainer"
      tags: [services, portainer]
      vars:
        traefik_http_rule_hostname: "portainer-001"

    - role: "deploy-mqtt-mosquitto"
      tags: [services, mqtt-mosquitto]
      vars:
        traefik_http_rule_hostname: "mqtt-001"
        mqtt_mosquitto_auth_enable: "true"
        mqtt_mosquitto_auth_refresh: false

    - role: "deploy-frigate"
      tags: [services, frigate]
      vars:
        traefik_http_rule_hostname: "frigate-001"

    - role: "deploy-zigbee2mqtt"
      tags: [services, zigbee2mqtt]

    - role: "deploy-zwave-js-ui"
      tags: [services, zwave-js-ui]

    - role: "deploy-rtl-433"
      tags: [services, rtl-433]

    - role: "deploy-meTube"
      tags: [services, meTube]

    - role: "deploy-digikam"
      tags: [services, digikam]

    - role: "deploy-authelia"
      tags: [services, authelia]
