---
- name: "PLAY: Copy Kube Config to local client"
  hosts: k3s_masters
  gather_facts: true
  become: true

  roles:
    - role: "kubernetes/k3s/clients/copy-kube-config"

- name: "PLAY: Configure local clients to connect to k3s cluster"
  hosts: localhost

  roles:
    - role: "kubernetes/k3s/clients/configure-local-clients-for-k3s-connection"
