---

- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ SERVICE_container_name }}"
  register: SERVICE_container_state

- name: "TASK: Set container facts"
  set_fact:
    SERVICE_container_exists: "{{ SERVICE_container_state.exists }}"
    SERVICE_container_image: "{{ SERVICE_container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    SERVICE_container_image_tag: "{{ SERVICE_container_image.split(':') }}"

- block:
    - include: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ SERVICE_image_base }}"
        tag: "{{ SERVICE_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "SERVICE_image_base_pull"

    - name: "TASK: Remove container for updates"
      community.docker.docker_container:
        name: "{{ SERVICE_container_name }}"
        container_default_behavior: "no_defaults"
        state: "absent"
      when: SERVICE_container_state.exists and SERVICE_image_base_pull.changed
  when: SERVICE_container_image_tag[1] != SERVICE_image_base_tag

- name: "TASK: Deploy {{ SERVICE_container_name }}"
  community.docker.docker_compose:
    project_src: "{{ docker_data_dir }}"
    build: "{{ 'yes' if SERVICE_image_base_pull.changed else 'no' }}"
    nocache: "no"
    state: "present"
