pihole_container_data_dir_sub_folders:
  - "etc-pihole/"
  - "mnt-backup/"
  - "scripts"

pihole_container_volumes:
  binds:
    - source: "./etc-pihole/"
      target: "/etc/pihole/"
    - source: "./mnt-backup/"
      target: "/mnt/backup/"
