authelia_container_data_dir_sub_folders:
  - "authelia-config/"
  - "authelia-secrets/"

authelia_container_volumes:
  binds:
    - source: "./authelia-config"
      target: "/config"
    - source: "./authelia-secrets"
      target: "/config/secrets:ro"
