authelia_container_data_dir: "{{ docker_container_root_dir }}/authelia"

authelia_image_base: "authelia/authelia"
authelia_image_base_tag: ""
# Ensures previous version of working
# authelia image is available for failback
authelia_image_base_tag_old: ""
authelia_container_name: "authelia"
# Controls whether docker-compose restarts Docker containers
authelia_container_restart: no
# Defines image ID for custom image
authelia_image_custom: "{{ ansible_user }}/authelia"

authelia_backup_directory: "/mnt/backup/"
authelia_nfs_backup_directory: "/nfs/Container-Data/docker/authelia/"
# Defines in days age of backups to remove
authelia_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
authelia_nfs_backup_frequency: "0 1 */15 * *"

authelia_container_envs:
  kv:
