authelia_container_data_dir: "{{ docker_container_root_dir }}/authelia"

authelia_image_base: "authelia/authelia"
authelia_image_base_tag: ""
# Ensures previous version of working
# authelia image is available for failback
authelia_image_base_tag_old: ""
authelia_container_name: "authelia"
# Controls whether docker-compose restarts Docker containers
authelia_container_restart: no
# Defines image ID for custom image
authelia_image_custom: "{{ ansible_user }}/authelia"

authelia_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.authelia1.rule=Host(`login.{{ home_lan_domain }}`)"
  - "traefik.http.routers.authelia1.entrypoints=websecure"
  - "traefik.http.routers.authelia1.middlewares=secureHeaders@file"
  - "traefik.http.routers.authelia1.service=authelia-svc"
  - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
  - "traefik.http.routers.authelia1.tls=true"
  - "traefik.http.routers.authelia1.tls.certresolver=letsEncrypt"

authelia_backup_directory: "/mnt/backup/"
authelia_nfs_backup_directory: "/nfs/Container-Data/docker/authelia/"
# Defines in days age of backups to remove
authelia_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
authelia_nfs_backup_frequency: "0 1 */15 * *"

authelia_container_envs:
  kv:
    TZ: "America/Vancouver"
    AUTHELIA_JWT_SECRET_FILE: "{{ authelia_secret_jwt_path }}"
    AUTHELIA_SESSION_SECRET_FILE: "{{ authelia_secret_session_path }}"
    AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: "{{ authelia_secret_notifier_smtp_password_file_path }}"

authelia_secret_jwt_path: "/config/secrets/jwt"
authelia_secret_session_path: "/config/secrets/session"
authelia_secret_notifier_smtp_password_file_path: "/config/secrets/email"
