stirling_pdf_container_data_dir_sub_folders:
  - "trainingData"
  - "extraConfigs"
  - "customFiles"
  - "logs"

stirling_pdf_container_volumes:
  binds:
    - source: "./trainingData"
      target: "/usr/share/tessdata"
    - source: "./extraConfigs"
      target: "/configs"
    - source: "./customFiles"
      target: "/customFiles/"
    - source: "./logs"
      target: "/logs/"
