wireguard_container_data_dir_sub_folders:
  - "wireguard_config"
  - "mnt-backup/"
  - "scripts"

wireguard_container_volumes:
  binds:
    - source: "./wireguard_config/"
      target: "/config"
    - source: "./mnt-backup/"
      target: "/mnt/backup/"
    - source: "/lib/modules"
      target: "/lib/modules"
