digikam_container_data_dir_sub_folders:
  - "digikam-config"
  - "digikam-config/Pictures"
  - "scripts"
  - "build"

digikam_container_volumes:
  binds:
    - source: "./digikam-config/"
      target: "/config"
