---
- name: "TASK: Verify backup directory"
  stat:
    path: "{{ paperless_ngx_nfs_backup_directory }}"
  register: stat_backup_dir

- name: "TASK: Assert backup directory exists"
  assert:
    that:
      - stat_backup_dir.stat.isdir is defined
      - stat_backup_dir.stat.isdir
    fail_msg: "Backup directory doesn't exist"
    success_msg: "Backup directory exists"

- name: "TASK: Create {{ paperless_ngx_container_name }} backup cron job"
  become: true
  template:
    src: paperless_ngx-backup.j2
    dest: "/etc/cron.d/paperless_ngx-backup"
    owner: root
    group: root
    mode: 0644

- name: "TASK: Create {{ paperless_ngx_container_name }} backup script"
  become: true
  template:
    src: "paperless_ngx-backup.sh.j2"
    dest: "{{ paperless_ngx_container_data_dir }}/scripts/paperless_ngx-backup.sh"
    owner: root
    group: root
    mode: 0755
