---
- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ wireguard_container_name }}"
  register: wireguard_container_state

- name: "TASK: Set container facts"
  set_fact:
    wireguard_container_exists: "{{ wireguard_container_state.exists }}"
    wireguard_container_image: "{{ wireguard_container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    wireguard_container_image_tag: "{{ wireguard_container_image.split(':') }}"

- block:
    - include_tasks: "wireguard_image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ wireguard_image_base }}"
        tag: "{{ wireguard_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "wireguard_image_base_pull"
  when: wireguard_container_image_tag[1] != wireguard_image_base_tag

- name: "TASK: Delete {{ wireguard_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ wireguard_container_data_dir }}"
    state: "absent"
  when: image_base_pull.changed or container_templated_files.changed
  register: container_deleted

- name: "TASK: Deploy {{ wireguard_container_name }}"
  community.docker.docker_compose:
    project_src: "{{ wireguard_container_data_dir }}"
    state: "{{ 'restarted' if wireguard_container_restart and not container_deleted.changed else 'present' }}"
