frigate_container_data_dir_sub_folders:
  - "media-frigate"

frigate_container_volumes:
  binds:
    - source: "./config.yml"
      target: "/config/config.yml"
    - source: "./media-frigate"
      target: "/media/frigate"
    - source: "/etc/localtime"
      target: "/etc/localtime:ro"
