---

docker:
  gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
  docker_ce_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"

system_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - python3-pip
  - python3-setuptools
  - snapd
  - software-properties-common
  - virtualbox-guest-dkms
  - virtualbox-guest-utils
  - virtualbox-guest-x11
  - virtualenv
  - xz-utils
  # pyATS - Required for psutil package building
  - python3.6-dev
  # Ubuntu-desktop requirements
  - firefox
  - gdm3
  - gnome-terminal
  - menu
  - ubuntu-desktop
  - xorg
  - xterm

system_snap_packages:
  - postman

system_pip_packages:
  - ansible
  - ansible-lint
  - docker-compose
  - ipython
  - napalm-ansible
  - pyats[full]
  - pynetbox
  - tabulate
  - yamllint
