---
- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ grafana_container_name }}"
  register: grafana_container_state

- name: "TASK: Set container facts"
  set_fact:
    grafana_container_exists: "{{ grafana_container_state.exists }}"
    grafana_container_image: "{{ grafana_container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    grafana_container_image_tag: "{{ grafana_container_image.split(':') }}"

- block:
    - include_tasks: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ grafana_image_base }}"
        tag: "{{ grafana_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "grafana_image_base_pull"

    - name: "TASK: Remove container for updates"
      community.docker.docker_container:
        name: "{{ grafana_container_name }}"
        container_default_behavior: "no_defaults"
        state: "absent"
      when: grafana_container_state.exists and grafana_image_base_pull.changed
  when: grafana_container_image_tag[1] != grafana_image_base_tag

- name: "TASK: Deploy {{ grafana_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_container_data_dir }}"
    state: "{{ 'restarted' if grafana_container_restart else 'present' }}"
