prometheus_container_data_dir: "{{ docker_container_root_dir }}/prometheus"

prometheus_image_base: "prom/prometheus"
prometheus_image_base_tag: ""
# Ensures previous version of working
# prometheus image is available for failback
prometheus_image_base_tag_old: ""
prometheus_container_name: "prometheus"
# Controls whether docker-compose restarts Docker containers
prometheus_container_restart: no

prometheus_container_envs:
  kv:

docker_cli_commands:
  "config.file": "/etc/prometheus/prometheus.yml"
  "web.config.file": "/etc/prometheus/web.yml"
  "web.console.libraries": "/usr/share/prometheus/console_libraries"
  "web.console.templates": "/usr/share/prometheus/consoles"


prometheus_global_scrape_interval: "1m"
prometheus_global_scrape_timeout: "10s"
prometheus_global_evaluation_interval: "1m"

prometheus_scrape_configs:
  - job_name: "DEFAULT_JOB"
    static_configs:
      targets:
      # Expects hostnames, and will resolve to IP for Prometheus
      # dig Lookup ran in prometheus.yml template
        - hosts:
            - ""
          labels:
    metrics_path: "/metrics"
    params:
    scrape_interval: ""
    scrape_timeout: ""
    relabel_configs:
