prometheus_container_data_dir: "{{ docker_container_root_dir }}/prometheus"

prometheus_image_base: "prom/prometheus"
prometheus_image_base_tag: ""
# Ensures previous version of working
# prometheus image is available for failback
prometheus_image_base_tag_old: ""
prometheus_container_name: "prometheus"
prometheus_container_web_port: "9090"
# Controls whether docker-compose restarts Docker containers
prometheus_container_restart: no

prometheus_container_envs:
  kv:

docker_cli_commands:
  "config.file": "/etc/prometheus/prometheus.yml"
  "web.config.file": "/etc/prometheus/web.yml"
  "web.console.libraries": "/usr/share/prometheus/console_libraries"
  "web.console.templates": "/usr/share/prometheus/consoles"


prometheus_global_scrape_interval: "1m"
prometheus_global_scrape_timeout: "10s"
prometheus_global_evaluation_interval: "1m"

# List of rule files
prometheus_rule_files:
  - ""

prometheus_scrape_configs:
  - job_name: "DEFAULT_JOB"
    static_configs:
      targets:
      # Expects hostnames, and will resolve to IP for Prometheus
      # dig Lookup ran in prometheus.yml template
        - hosts:
            - hostname: ""
              port: ""
          labels:
    metrics_path: "/metrics"
    basic_auth:
      username: ""
      password: ""
    params:
    scrape_interval: ""
    scrape_timeout: ""
    relabel_configs:

prometheus_alerting_groups:
  - group_name: "websites"
    rules:
      - alert_name: "websiteDown"
        expr: "http_response_http_response_code != 200"
        for: "1m"
        labels:
          severity: "critical"
        annotations:
          summary: "{{ '{{ $labels.instance }} is having issues' }}"
