docker_data_dir: "{{ docker_user_root_dir }}/SERVICE"

image_base: "SERVICE/SERVICE"
container_name: "SERVICE"
# Controls whether docker-compose restarts Docker containers
container_restart: no
image_custom: "{{ ansible_user }}/SERVICE"

backup_directory: "/mnt/backup/"
nfs_backup_directory: "/nfs/Container-Data/docker/SERVICE/"
# Defines in days age of backups to remove
nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
nfs_backup_frequency: "0 1 */15 * *"

docker_envs:
  kv:
