traefik_container_data_dir: "{{ docker_container_root_dir }}/traefik"

traefik_image_base: "traefik"
traefik_image_base_tag: ""
# Ensures previous version of working
# traefik image is available for failback
traefik_image_base_tag_old: ""
traefik_container_name: "traefik"
# Controls whether docker-compose restarts Docker containers
traefik_container_restart: no

traefik_container_dns_externally_used: false
traefik_container_dns_servers: []

traefik_logging_directory: "/var/log/traefik"

traefik_container_envs:
  kv:
    CF_DNS_API_TOKEN: "{{ dns_provider_api_token }}"

traefik_http_rule_hostname: "traefik"
traefik_label_configurations: []
