paperless_ngx_container_data_dir: "{{ docker_container_root_dir }}/paperless_ngx"

paperless_ngx_image_base: "REPO/paperless_ngx"
paperless_ngx_image_base_tag: ""
# Ensures previous version of working
# paperless_ngx image is available for failback
paperless_ngx_image_base_tag_old: ""
paperless_ngx_container_name: "paperless_ngx"
# Controls whether docker-compose restarts Docker containers
paperless_ngx_container_restart: no
# Defines image ID for custom image
paperless_ngx_image_custom: "{{ ansible_user }}/paperless_ngx"

paperless_ngx_container_labels: []

paperless_ngx_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.paperless_ngx1.rule=Host(`paperless_ngx.{{ home_lan_domain }}`)"
  - "traefik.http.routers.paperless_ngx1.entrypoints=websecure"
  - "traefik.http.routers.paperless_ngx1.middlewares=lanWhitelist@file,secureHeaders@file"
  - "traefik.http.routers.paperless_ngx1.tls=true"
  - "traefik.http.routers.paperless_ngx1.tls.certresolver=letsEncrypt"

paperless_ngx_backup_directory: "/mnt/backup/"
paperless_ngx_nfs_backup_directory: "/nfs/Container-Data/docker/paperless_ngx/"
# Defines in days age of backups to remove
paperless_ngx_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
paperless_ngx_nfs_backup_frequency: "0 1 */15 * *"

paperless_ngx_container_envs:
  kv:
