SERVICE__container_data_dir: "{{ docker_container_root_dir }}/SERVICE_"

SERVICE__image_base: "REPO/SERVICE_"
SERVICE__image_base_tag: ""
# Ensures previous version of working
# SERVICE_ image is available for failback
SERVICE__image_base_tag_old: ""
SERVICE__container_name: "SERVICE_"
# Controls whether docker-compose restarts Docker containers
SERVICE__container_restart: no
# Defines image ID for custom image
SERVICE__image_custom: "{{ ansible_user }}/SERVICE_"

SERVICE__container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.SERVICE_1.rule=Host(`SERVICE_.{{ home_lan_domain }}`)"
  - "traefik.http.routers.SERVICE_1.entrypoints=websecure"
  - "traefik.http.routers.SERVICE_1.middlewares=lanWhitelist@file,secureHeaders@file"
  - "traefik.http.routers.SERVICE_1.tls=true"
  - "traefik.http.routers.SERVICE_1.tls.certresolver=letsEncrypt"

SERVICE__backup_directory: "/mnt/backup/"
SERVICE__nfs_backup_directory: "/nfs/Container-Data/docker/SERVICE_/"
# Defines in days age of backups to remove
SERVICE__nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
SERVICE__nfs_backup_frequency: "0 1 */15 * *"

SERVICE__container_envs:
  kv:
