docker_data_dir: "{{ docker_user_root_dir }}/smtp_relay"

smtp_relay_image_base: "smtp_relay/smtp_relay"
smtp_relay_container_name: "smtp_relay"
pihole_image_custom: "{{ ansible_user }}/smtp_relay"

smtp_relay_external_ip_mapping: "{{ home_lan_dns_servers[0] }}"

smtp_relay_envs:
  kv:
