mqtt-mosquitto_container_data_dir: "{{ docker_container_root_dir }}/mqtt-mosquitto"

mqtt-mosquitto_image_base: "eclipse-mosquitto"
mqtt-mosquitto_image_base_tag: ""
# Ensures previous version of working
# mqtt-mosquitto image is available for failback
mqtt-mosquitto_image_base_tag_old: ""
mqtt-mosquitto_container_name: "mqtt-mosquitto"
# Controls whether docker-compose restarts Docker containers
mqtt-mosquitto_container_restart: no
# Defines image ID for custom image
mqtt-mosquitto_image_custom: "{{ ansible_user }}/mqtt-mosquitto"

# Ports
mqtt_mosquitto_port_tcp: 1883
mqtt_mosquitto_port_web_socket: 9001

mqtt-mosquitto_backup_directory: "/mnt/backup/"
mqtt-mosquitto_nfs_backup_directory: "/nfs/Container-Data/docker/mqtt-mosquitto/"
# Defines in days age of backups to remove
mqtt-mosquitto_nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
mqtt-mosquitto_nfs_backup_frequency: "0 1 */15 * *"

mqtt-mosquitto_container_envs:
  kv:
