---
pihole_orbital_sync_use_custom_dns: true
pihole_orbital_sync_custom_dns_servers:
  - "pihole.{{ home_lan_domain }}"
  - "pihole2.{{ home_lan_domain }}"

pihole_orbital_sync_container_envs:
  kv:
    PRIMARY_HOST_BASE_URL: "https://pihole.{{ home_lan_domain }}"
    PRIMARY_HOST_PASSWORD: "{{ docker_services_admin_password }}"
    SECONDARY_HOSTS_1_BASE_URL: "https://pihole2.{{ home_lan_domain }}"
    SECONDARY_HOSTS_1_PASSWORD: "{{ docker_services_admin_password }}"
    NOTIFY_ON_SUCCESS: "false"
    NOTIFY_ON_FAILURE: "true"
    NOTIFY_SMTP_ENABLED: "true"
    NOTIFY_SMTP_FROM: "monitoring.notifications@m.{{ home_lan_domain_public }}"
    NOTIFY_SMTP_TO: "services+monitoring@{{ home_lan_domain_public}}"
    NOTIFY_SMTP_HOST: "{{ smtp_monitoring_server_url }}"
    NOTIFY_SMTP_TLS: "true"
    NOTIFY_SMTP_PORT: "{{ smtp_monitoring_server_port }}"
    NOTIFY_SMTP_USER: "apikey"
    NOTIFY_SMTP_PASSWORD: "{{ smtp_monitoring_api_key }}"
