docker_data_dir: "{{ docker_user_root_dir }}/snmp_exporter"

image_base: "prom/snmp-exporter"
container_name: "snmp_exporter"
# Used to determine if to restart containers
container_restarted: "no"

docker_envs:
  kv:

prometheus_mib_modules:
  - name: ""
    walk:
      - ""
    version: ""
    max_repetitions: ""
    retries: ""
    timeout: ""
    auth:
      community: ""
      username: ""
      security_level: ""
      password: ""
      auth_protocol: ""
      priv_protocol: ""
      priv_password: ""
      context_name: ""
    lookups:
      - source_indexes: []
        lookup: ""
        drop_source_indexes: ""
