docker_data_dir: "{{ docker_container_root_dir }}/snmp_exporter"

image_base: "prom/snmp-exporter"
image_base_tag: ""
# Ensures previous version of working
# snmp_exporter image is available for failback
image_base_tag_old: ""
container_name: "snmp_exporter"
# Controls whether docker-compose restarts Docker containers
container_restart: no

docker_envs:
  kv:

prometheus_mib_modules:
  - name: ""
    walk:
      - ""
    version: ""
    max_repetitions: ""
    retries: ""
    timeout: ""
    auth:
      community: ""
      username: ""
      security_level: ""
      password: ""
      auth_protocol: ""
      priv_protocol: ""
      priv_password: ""
      context_name: ""
    lookups:
      - source_indexes: []
        lookup: ""
        drop_source_indexes: ""
