pihole_orbital_sync_container_data_dir: "{{ docker_container_root_dir }}/pihole_orbital_sync"

pihole_orbital_sync_image_base: "mattwebbio/orbital-sync"
pihole_orbital_sync_image_base_tag: ""
# Ensures previous version of working
# pihole_orbital_sync image is available for failback
pihole_orbital_sync_image_base_tag_old: ""
pihole_orbital_sync_container_name: "pihole_orbital_sync"
# Controls whether docker-compose restarts Docker containers
pihole_orbital_sync_container_restart: no
# Defines image ID for custom image
pihole_orbital_sync_image_custom: "{{ ansible_user }}/pihole_orbital_sync"

pihole_orbital_sync_container_labels: []

pihole_orbital_sync_container_traefik_labels: []

pihole_orbital_sync_container_envs:
  kv:
