zigbee2mqtt_container_data_dir_sub_folders:
  - "zigbee2mqtt-data/"

zigbee2mqtt_container_volumes:
  binds:
    - source: "./zigbee2mqtt-data/"
      target: "/app/data"
    - source: "/run/udev"
      target: "/run/udev:ro"
