---


### Prometheus
prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      targets:
      # Expects hostnames, and will resolve to IP for Prometheus
      # dig Lookup ran in prometheus.yml template
        - hosts:
            - hostname: "localhost"
              port: "9090"
    metrics_path: "/metrics"
    basic_auth:
      username: "{{ docker_services_admin_username }}"
      password: "{{ docker_services_admin_password }}"
    scrape_interval: "15s"
    scrape_timeout: "5s"
  - job_name: "node_exporters"
    static_configs:
      targets:
      # Expects hostnames, and will resolve to IP for Prometheus
      # dig Lookup ran in prometheus.yml template
        - hosts:
            - hostname: "rbp4-001.{{ home_lan_domain }}"
              port: "9100"
          labels:
            device_type: "rbp4"
    metrics_path: "/metrics"
    scrape_interval: "1m"
    scrape_timeout: "5s"
  - job_name: "snmp_printers"
    static_configs:
      targets:
      # Expects hostnames, and will resolve to IP for Prometheus
      # dig Lookup ran in prometheus.yml template
        - hosts:
            - hostname: "printer.{{ home_lan_domain }}"
              port: ""
          labels:
            device_type: "printer"
    metrics_path: "/snmp"
    params:
      module: "[PRINTER-MIB]"
    scrape_interval: "1m"
    scrape_timeout: "5s"
    relabel_configs:
      - source_labels: "[__address__]"
        target_label: "__param_target"
      - source_labels: "[__param_target]"
        target_label: "instance"
      - target_label: "__address__"
        replacement: "snmp_exporter:9116"

### Node_Exporter
prometheus_node_exporter_version: "1.2.2"

### SNMP
snmp_exporter_prometheus_mib_modules:
  - name: "PRINTER-MIB"
    walk:
      - "prtMarkerSuppliesLevel"
      - "prtMarkerSuppliesMaxCapacity"
      - "hrDeviceStatus"
      - "hrPrinterStatus"
    version: "2"
    max_repetitions: "25"
    retries: "3"
    timeout: "5s"
    auth:
      community: "{{ snmp_community_strings.printer }}"
    lookups:
      - source_indexes: [hrDeviceIndex]
        lookup: hrDeviceDescr
        drop_source_indexes: true
