---

### Node_Exporter
prometheus_node_exporter_version: "1.2.2"

### SNMP
snmp_exporter_prometheus_mib_modules:
  - name: "PRINTER-MIB"
    walk:
      - "prtMarkerSuppliesLevel"
      - "prtMarkerSuppliesMaxCapacity"
      - "hrDeviceStatus"
      - "hrPrinterStatus"
    version: "2"
    max_repetitions: "25"
    retries: "3"
    timeout: "5s"
    auth:
      community: "{{ snmp_community_strings.printer }}"
    lookups:
      - source_indexes: [hrDeviceIndex]
        lookup: hrDeviceDescr
        drop_source_indexes: true
    overrides:
  - name: "QNAP-MIB"
    walk:
      - cpuUsage
      - systemCPU-UsageEX
      - systemFreeMemEX
      - systemFreeMem
      - systemUsedMemory
      - systemAvailableMem
      - systemUptimeEX
      - systemTemperatureEX
      - enclosureSystemTemp
      - ifPacketsReceivedEX
      - ifPacketsSentEX
      - sysFanSpeedEX
      - sysVolumeFreeSizeEX
      - sysVolumeStatusEX
      - diskTemperture
      - diskSmartInfo
      - diskStatus
      - volumeStatus
      - iops
      - latency
    version: "2"
    max_repetitions: "25"
    retries: "3"
    timeout: "5s"
    auth:
      community: "{{ snmp_community_strings.qnap }}"
    lookups:
    overrides:
      - metric_name: "diskStatus"
        type: "DisplayString"
      - metric_name: "volumeStatus"
        type: "DisplayString"
  - name: "QNAP-LONG-MIB"
    walk:
      - modelNameEX
      - hostNameEX
      - firmwareVersion
      - firmwareUpgradeAvailable
      - sysVolumeDescrEX
      - sysVolumeTotalSizeEX
      - diskModel
      - diskCapacity
      - diskSerialNumber
      - diskManufacturer
      - volumeName
      - volumeCapacity
    version: "2"
    max_repetitions: "25"
    retries: "3"
    timeout: "5s"
    auth:
      community: "{{ snmp_community_strings.qnap }}"
    lookups:
    overrides:
      - metric_name: "modelNameEX"
        type: "DisplayString"
      - metric_name: "hostNameEX"
        type: "DisplayString"
      - metric_name: "firmwareVersion"
        type: "DisplayString"
      - metric_name: "sysVolumeDescrEX"
        type: "DisplayString"
      - metric_name: "diskModel"
        type: "DisplayString"
      - metric_name: "diskType"
        type: "DisplayString"
      - metric_name: "diskManufacturer"
        type: "DisplayString"
      - metric_name: "volumeName"
        type: "DisplayString"
