all:
  children:
    docker_hosts:
      hosts:
        "rbp4-001":
    raspberry_pi_servers:
      hosts:
        "rbp4-001":
    nas:
      hosts:
        "nas1":
    services_monitoring:
      hosts:
        "rbp4-001": 
