---
- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ pihole_container_name }}"
  register: pihole_container_state

- name: "TASK: Set container facts"
  set_fact:
    pihole_container_exists: "{{ pihole_container_state.exists }}"
    pihole_container_image: "{{ pihole_container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    pihole_container_image_tag: "{{ pihole_container_image.split(':') }}"

- block:
    - include_tasks: "pihole_image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ pihole_image_base }}"
        tag: "{{ pihole_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "image_base_pull"
  when: pihole_container_image_tag[1] != pihole_image_base_tag

- name: "TASK: Delete {{ pihole_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ pihole_container_data_dir }}"
    state: "absent"
  when: image_base_pull.changed or container_templated_files.changed
  register: container_deleted

- name: "TASK: Deploy {{ pihole_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ pihole_container_data_dir }}"
    build: "{{ 'always' if image_base_pull.changed else 'never' }}"
    state: "{{ 'restarted' if pihole_container_restart and not container_deleted.changed else 'present' }}"
