- name: "Template script for suspending acpi devices"
  become: true
  template:
    src: "ubuntu-disable_acpi_wakeup_devices.sh.j2"
    dest: "/usr/local/bin/disable_acpi_wakeup_devices.sh"
    mode: 0750
    owner: "root"
    group: "root"

- name: "Add crontab entry for running acpi device suspend script"
  become: true
  cron:
    name: "ACPI Device Auto Suspend at Boot"
    special_time: "reboot"
    user: "root"
    job: "/usr/local/bin/disable_acpi_wakeup_devices.sh"
    cron_file: "disable_acpi_wakeup_devices"
    state: "present"
