frigate_container_data_dir: "{{ docker_container_root_dir }}/frigate"

frigate_image_base: "ghcr.io/blakeblackshear/frigate"
frigate_image_base_tag: ""
# Ensures previous version of working
# frigate image is available for failback
frigate_image_base_tag_old: ""
frigate_container_name: "frigate"
# Controls whether docker-compose restarts Docker containers
frigate_container_restart: no
# Defines image ID for custom image
frigate_image_custom: "{{ ansible_user }}/frigate"

frigate_container_traefik_labels:
  - "traefik.enable=true"
  - "traefik.docker.network={{ docker_networks.proxy.name }}"
  - "traefik.http.routers.frigate1.rule=Host(`{{ traefik_http_rule_hostname }}.{{ home_lan_domain }}`)"
  - "traefik.http.routers.frigate1.entrypoints=websecure"
  - "traefik.http.routers.frigate1.middlewares=secureHeaders@file"
  - "traefik.http.routers.frigate1.service=frigate-svc"
  - "traefik.http.services.frigate-svc.loadbalancer.server.port={{ frigate_port_web }}"
  - "traefik.http.routers.frigate1.tls=true"
  - "traefik.http.routers.frigate1.tls.certresolver=letsEncrypt"

#### Ports
# Web port will be mapped by traefik
frigate_port_web: 5000
frigate_port_rtsp: 8554
frigate_port_webrtc: 8555

frigate_plus_api_key: ""

frigate_container_envs:
  kv:
    # Used for RTSP connections to cameras
    FRIGATE_RTSP_PASSWORD: "{{ frigate_rtsp_password }}"
    PLUS_API_KEY: "{{ frigate_plus_api_key }}"

traefik_http_rule_hostname: "frigate"

frigate_container_data_dir_sub_folders:
  - "frigate-config"
  - "media-frigate"

frigate_container_volumes:
  binds:
    - source: "./frigate-config"
      target: "/config"
    - source: "./media-frigate"
      target: "/media/frigate"
    - source: "/etc/localtime"
      target: "/etc/localtime:ro"
