docker_gpg_key_url: "https://download.docker.com/linux/{{ ansible_distribution |  lower }}/gpg"

docker_repo_filename: "docker"
docker_repo_type: "stable"
docker_repo_name: "deb [arch={{ cpu_architecture_mappings[ansible_architecture] }}] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_repo_type }}"

docker_data_root_dir: "/var/lib/docker"

docker_daemon_config:
  - data-root: "{{ docker_data_root }}"
