ryot_media_container_data_dir_sub_folders:
  - "ryot_config"
  - "ryot_db_data"

ryot_media_container_volumes:
  binds:
    - source: "./ryot_config"
      target: "/home/ryot/config/"

ryot_media_db_container_volumes:
  binds:
    - source: "./ryot_db_data"
      target: "/var/lib/postgresql/data"
