---
- name: "TASK: Retrieve container info"
  community.docker.docker_container_info:
    name: "{{ frigate_container_name }}"
  register: container_state

- name: "TASK: Set container facts"
  set_fact:
    container_exists: "{{ container_state.exists }}"
    container_image: "{{ container_state.container.Config.Image | default('tag:n/a') }}"

- name: "TASK: Set container image tag"
  set_fact:
    container_image_tag: "{{ container_image.split(':') }}"

- block:
    - include_tasks: "image_cleanup.yml"

    - name: "TASK: Pull base image"
      community.docker.docker_image:
        name: "{{ frigate_image_base }}"
        tag: "{{ frigate_image_base_tag }}"
        source: "pull"
        state: "present"
      register: "image_base_pull"

    - name: "TASK: Remove container for updates"
      community.docker.docker_container:
        name: "{{ frigate_container_name }}"
        container_default_behavior: "no_defaults"
        state: "absent"
      when: container_exists and image_base_pull.changed
  when: container_image_tag[1] != frigate_image_base_tag

- name: "TASK: Deploy {{ frigate_container_name }}"
  community.docker.docker_compose_v2:
    project_src: "{{ frigate_container_data_dir }}"
    state: "{{ 'restarted' if frigate_container_restart else 'present' }}"
