---
- name: "Create root folder for container"
  become: true
  file:
    path: "{{ frigate_container_data_dir }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"

- name: "Create folders for build and container data"
  become: true
  file:
    path: "{{ frigate_container_data_dir }}/{{ item }}"
    owner: "root"
    group: "docker"
    mode: 0775
    state: "directory"
  with_items: "{{ frigate_container_data_dir_sub_folders }}"

- name: "Template files for building and running {{ frigate_container_name }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "docker"
    mode: 0660
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ frigate_container_data_dir }}/docker-compose.yml"
    - src: "frigate.env.j2"
      dest: "{{ frigate_container_data_dir }}/frigate.env"
    - src: "frigate-config.yml.j2"
      dest: "{{ frigate_container_data_dir }}/frigate-config/config.yml"
  loop_control:
    label: "{{ item.src }}"
  register: "container_templated_files"

- name: "Deploy custom go2rtc version"
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/AlexxIT/go2rtc/releases/download/v{{ frigate_custom_go2rtc_version }}/go2rtc_{{ ansible_system | lower }}_{{ cpu_architecture_mappings[ansible_architecture] }}"
    dest: "{{ frigate_container_data_dir }}/frigate-config/go2rtc"
    mode: 0770
    owner: "root"
    group: "docker"
  when: "frigate_use_custom_go2rtc"
  register: "download_custom_go2rtc"

- name: "TASK: Set containers to restart when templated files change"
  set_fact:
    frigate_container_restart: "yes"
  when: "container_templated_files.changed or download_custom_go2rtc.changed"
