snmp_exporter_container_data_dir_sub_folders:
  - "temp"
  - "snmp_generator"

snmp_exporter_container_volumes:
  binds:
    - source: "./snmp_generator/snmp.yml"
      target: "/etc/snmp_exporter/snmp.yml"
