SERVICE__container_data_dir: "{{ docker_container_root_dir }}/SERVICE_"

SERVICE__image_base: "SERVICE_/SERVICE_"
SERVICE__image_base_tag: ""
# Ensures previous version of working
# SERVICE_ image is available for failback
SERVICE__image_base_tag_old: ""
SERVICE__container_name: "SERVICE_"
# Controls whether docker-compose restarts Docker containers
SERVICE__container_restart: no
SERVICE__image_custom: "{{ ansible_user }}/SERVICE_"

SERVICE__backup_directory: "/mnt/backup/"
SERVICE__nfs_backup_directory: "/nfs/Container-Data/docker/SERVICE/"
# Defines in days age of backups to remove
SERVICE__nfs_backup_cleanup_period: "60"
# Defines via cron syntax how often to run backup
SERVICE__nfs_backup_frequency: "0 1 */15 * *"

SERVICE__docker_envs:
  kv:
