---
postfix_config_relay_host: ""
postfix_config_smtp_use_tls: "yes"
postfix_config_smtp_sasl_auth_enable: "yes"
postfix_config_sasl_file_path: "/etc/postfix/sasl_passwd"
postfix_config_smtp_sasl_password_maps: "hash:{{ postfix_config_sasl_file_path }}"
postfix_config_smtp_tls_CApath: "/etc/ssl/certs"
postfix_config_smtp_sasl_security_options: "noanonymous, noplaintext"
postfix_config_smtp_sasl_tls_security_options: "noanonymous"
postfix_config_smtp_tls_wrappermode: "yes"
postfix_config_smtp_tls_security_level: "encrypt"

# Is the recipient for the sent emails
postfix_root_alias_email: "monitoring.notifications@m.{{ home_lan_domain_public }}"
