---

- name: "Create folders for pihole build and container data"
  file:
    path: "{{ item }}"
  with_items:
    - "{{ docker_data_dir }}/build"
    - "{{ docker_data_dir }}/etc-dnsmasq.d"
    - "{{ docker_data_dir }}/etc-pihole"
    - "{{ docker_data_dir }}/etc-pihole-updatelists"

- name: "Template files for building and running PiHole"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "docker"
    mode: 0664
  with_items:
    - src: "docker-compose.yml.j2"
      dest: "{{ docker_data_dir }}/docker-compose.yml"
    - src: "pi-hole.env.j2"
      dest: "{{ docker_data_dir }}/pi-hole.env"
    - src: "Dockerfile.j2"
      dest: "{{ docker_data_dir }}/build/Dockerfile"
  loop_control:
    label: "{{ item.src }}"

- name: "TASK: Populate pihole_updatelists config"
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ docker_data_dir }}/etc-pihole-updatelists"
  with_fileglob: "files/pihole_updatelists_conf/*"
  loop_control:
    label: "{{ item | basename }}"
