---

- name: "TASK: Verify if pihole container is already running"
  community.docker.docker_container_info:
    name: "{{ pihole_container_name }}"
  register: pihole_container_state

- name: "TASK: Pull base pihole image"
  community.docker.docker_image:
    name: "{{ pihole_image_base }}"
    tag: "{{ pihole_image_base_tag }}"
    source: "pull"
    state: "present"
  register: "pihole_image_base_pull"

- name: "TASK: Deploy pihole"
  community.docker.docker_compose:
    project_src: "{{ docker_data_dir }}"
    build: "{{ 'yes' if pihole_image_base_pull.changed else 'no' }}"
    nocache: "no"
    state: "present"
