portainer_container_data_dir: "{{ docker_container_root_dir }}/portainer"

portainer_image_base: "portainer/portainer-ce"
portainer_image_base_tag: ""
# Ensures previous version of working
# portainer image is available for failback
portainer_image_base_tag_old: ""
portainer_container_name: "portainer"
# Controls whether docker-compose restarts Docker containers
portainer_container_restart: no
# Defines image ID for custom image
portainer_image_custom: "{{ ansible_user }}/portainer"
portainer_container_web_port: "9000"

portainer_container_envs:
  kv:

traefik_http_rule_hostname: "portainer"
